### ISSUE TITLE
A new "Dialog Card" type in addition to Term and Kanji

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#100]
Sometimes I find sentences that do not contain new vocabulary that I still want to review in Anki, because the grammar or overall usage is interesting. I think it could be very helpful for Memento to include a new card type (that maps to the user's Anki card type) for dialogue.

I think a dialog card can basically be a term card that does not require any term to be selected when adding to Anki. The user can map the markers themselves (e.g., {screenshot} and {audio-context} on the front, {context} additionally on the back). An add button (possibly in the subtitle list area), right clicking on context, or a key bind could all work very well.

**Comment by Calvin-Xu** [comment]
After some thought, I feel like this doesn't really need a new card type. Since the image, context and audio context can be copied quite easily in Memento, it's not hard to make such cards by hand.

However, one thing impeding such a workflow right now is that copied audio context is not volume normalized, which is just very problematic for videos with off levels of volume (https://github.com/ripose-jp/Memento/issues/63).

I think it could be of value to enable normalizing (& and possibly padding audio) if the user has Anki integration enabled, with the current behavior to fall back on. It might be a more versatile feature.

**Comment by ripose-jp** [comment]
Term cards are intuitively added from term searches and kanji cards are added from kanji searches. The biggest problem for dialog cards is the question of where would I put the UI element for creating them? Not to mention you can already put sentences on the front of term cards and kanji cards if you wanted this sort of workflow.

**Comment by Calvin-Xu** [comment]
> The biggest problem for dialog cards is the question of where would I put the UI element for creating them

I think so too. Hence I feel just making any Anki Integration audio settings (if enabled) apply to copying audio context is a better idea now. The card can then be made manually.

> you can already put sentences on the front of term cards and kanji cards if you wanted this sort of workflow

I am envisioning more along the lines of "listening drill" cards where the dialog audio is played on the front side and the dialog text on the back side, (and with the relevant screenshots, etc).

For dialog that do not have any new words or kanji, saving it via a term or kanji card can lead to duplicates. Also, my actual term cards have the context on the back, and it's nicer to keep them this way.

**Comment by ripose-jp** [comment]
>I am envisioning more along the lines of "listening drill" cards where the dialog audio is played on the front side and the dialog text on the back side, (and with the relevant screenshots, etc).

There's nothing stopping you from doing this with term cards.

>Also, my actual term cards have the context on the back, and it's nicer to keep them this way.

You can create a new profile and swap between them depending on what kind of card you want to create.

**Comment by Calvin-Xu** [comment]
> You can create a new profile and swap between them depending on what kind of card you want to create.

Wow, I certainly have not thought of this. This definitely could work very well. Thanks!

Still, I'm now feeling that copying audio context with padding and normalization settings applied can be helpful for other situations. Something I've been doing in my workflow of creating term cards is to by default include the audio of just the sentence the term is in. If I feel it is necessary, I additionally copy & add it to Anki a much longer clip for complete context and more listening drill. If during review I want to be on faster pace, I just skip the second audio clip, but otherwise I listen to the whole thing. Because the sentence breaks of subtitles can be fairly arbitrary, I rely on {audio-context} to adjust the range of both clips.

This way it is quite important to have identical audio settings for copying. I've opened a PR for what I'm using: https://github.com/ripose-jp/Memento/pull/103 and I'll close this issue.
