### ISSUE TITLE
Inflection normalization issues

### ISSUE THREAD

**Issue by aemino** [ripose-jp/Memento#101]
After packaging Memento for NixOS, I noticed that there is a regression in inflection normalization compared to the AppImage version. See the following images for an example (first is self-compiled, second is AppImage):

![image](https://user-images.githubusercontent.com/13167687/163867696-dd188acf-9d2b-4121-af10-65b91fb1c262.png)
![image](https://user-images.githubusercontent.com/13167687/163867790-ce0ed479-4583-40b5-a51b-992f549ee240.png)

In this same line, the AppImage version is able to pick out 暴れる, while the self-compiled version only matches the term 暴. Given that the AppImage version works fine, it seems like this is not an issue with Memento itself but rather the self-compiled setup on my end. However, I'm not familiar enough with how Memento works to determine what the issue is myself. Could the issue be related to MeCab? As far as I can tell, the Nix package for MeCab is using the latest version and includes ipadic.

**Comment by ripose-jp** [comment]
Can you run MeCab from your console and input 振り回して? Post how it tokenizes it.

**Comment by aemino** [comment]
![image](https://user-images.githubusercontent.com/13167687/163871105-cdbec71b-770a-4458-ae5c-d76d17d5d355.png)
This looks odd.

**Comment by ripose-jp** [comment]
Is your system locale UTF-8?
https://stackoverflow.com/questions/58211879/nixos-how-to-granularly-configure-locale-settings

**Comment by aemino** [comment]
Yes, should be. I have `i18n.defaultLocale = "en_US.UTF-8"` set, and this is the output of running `locale`:
![image](https://user-images.githubusercontent.com/13167687/163872045-bb62532c-515a-4280-81a2-f1bf275d2644.png)

**Comment by ripose-jp** [comment]
Try doing running MeCab with these options and inputting 振り回して. What is the output?
```
mecab -r /path/to/Memento-Git-Directory/dic/ipadic/dicrc -d /path/to/Memento-Git-Directory/dic/ipadic/
```

**Comment by aemino** [comment]
Seems to work fine.
![image](https://user-images.githubusercontent.com/13167687/163873052-bd2296b6-8cdc-4ec8-99fb-a4c5d3a89f39.png)

**Comment by ripose-jp** [comment]
There's probably some sort of encoding issue with the MeCab system dictionary bundled with NixOS.

The easiest fix would be to change `dicdir` in `/etc/mecabrc` to point to a functioning ipadic version like the one bundled with Memento. I believe this is a problem with the MeCab/ipadic packages on NixOS and should probably be brought to the maintainer's attention.

**Comment by aemino** [comment]
Okay, good news. I patched the MeCab package so that it applies `--with-charset=utf-8` when configuring `ipadic`. This seems to resolve the issue. I'll upstream this to nixpkgs... \~sometime\~. Thank you for the help diagnosing this!

**Comment by nonetrix** [comment]
> Okay, good news. I patched the MeCab package so that it applies `--with-charset=utf-8` when configuring `ipadic`. This seems to resolve the issue.
> 
> ![image](https://user-images.githubusercontent.com/13167687/163936228-a8196b5f-c0b9-46d6-9f3f-bf2e5b0b8e47.png)
> 
> I'll upstream this to nixpkgs... ~sometime~. Thank you for the help diagnosing this!

Any updates?
