### ISSUE TITLE
Fullscreen stutter on macOS

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#104]
It seems that opening a video with Memento and making it fullscreen results in stutter and this message on macOS:

```
Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).
```

(sometimes also `Audio device underrun detected.`)

I am finally reporting this now for 2 reasons:

1. The effect is more noticeable on a machine with just HD630 that I've been using more. I don't think I ever noticed anything on machines with better (discrete) graphics.
2. More importantly, the stutter immediately goes away when I open the subtitle list widget (regardless of whether any subtitles are loaded; or the search window on Ctrl-R); since I almost always have the subtitle list open, I probably didn't run into this issue before. However, the stutter returns after closing active Memento UI elements (the subtitle list or the search window).

Given the 2nd reason, the issue is not posing any obstacles for my usage. I am not sure if it has always been there, but possibly a problem with the fullscreen solution for macOS?

**Comment by ripose-jp** [comment]
Works on my MacBook Air. I don't really have the hardware to test this sort of issue.

Anyway, there are quirks with mpv where if a frame is detected as dropped it could potentially desync things internally in mpv. This can happen in a few cases in macOS, for example minimizing Memento while playing video or fullscreening Memento and then switching to another window while playing video. This isn't really something I can fix because Qt doesn't expose anything in the API that tells me whether or not calling `update()` will cause `paintGL()` to be called.

I base this analysis on this comment by wm4.
```
    /* If the Qt window is not visible, Qt's update() will just skip rendering.
     * This confuses mpv's render API, and may lead to small occasional
     * freezes due to video rendering timing out.
     * Handle this by manually redrawing.
     * Note: Qt doesn't seem to provide a way to query whether update() will
     *       be skipped, and the following code still fails when e.g. switching
     *       to a different workspace with a reparenting window manager.
     */
```

Does pausing and unpausing fix the desync?

**Comment by Calvin-Xu** [comment]
> Does pausing and unpausing fix the desync?

Sadly no.

> Works on my MacBook Air. I don't really have the hardware to test this sort of issue.

I noticed this on my Hackintosh setup with HD630 (which otherwise works fine). On my MBP I also get the desync message, but it seems that fewer frames are dropped, and it's overall smoother with no audio issues, so I probably never paid attention as I always open the subtitle list and blame any initial stutter on my SMB connection.

**Comment by Calvin-Xu** [comment]
So it seems that opening a video with Memento already fullscreen has stutters too. Here's an example.

```
 (+) Video --vid=1 (*) (hevc 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) (flac 2ch 48000Hz)
Using hardware decoding (videotoolbox).
AO: [coreaudio] 48000Hz stereo 2ch s32
VO: [libmpv] 1920x1080 videotoolbox[p010]
AV: 00:00:02 / 00:24:12 (0%) A-V:  0.000 Dropped: 44
Audio device underrun detected.
AV: 00:00:02 / 00:24:12 (0%) A-V:  0.087 Dropped: 57
Audio device underrun detected.
AV: 00:00:04 / 00:24:12 (0%) A-V:  0.000 Dropped: 95
Audio device underrun detected.
AV: 00:00:04 / 00:24:12 (0%) A-V:  0.197 Dropped: 96
Audio device underrun detected.
AV: 00:00:05 / 00:24:12 (0%) A-V:  0.228 Dropped: 100
Audio device underrun detected.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:05 / 00:24:12 (0%) A-V:  0.502 Dropped: 101
Audio device underrun detected.
AV: 00:00:05 / 00:24:12 (0%) A-V:  0.694 Dropped: 101
Audio device underrun detected.
(Paused) AV: 00:00:03 / 00:24:12 (0%) A-V:  0.000
```

Given that rendering some UI elements seem to remedy this, I imagine there might be some kind of hack possible (like the 1px border on Windows), but I don't think I'd be willing to put up with visual oddities as having the subtitle list open works well. So tbh I think can't fix for now works if that is the case.

**Comment by ripose-jp** [comment]
Is this only reproducible on your Hackintosh or does Apple hardware have the same issue?

**Comment by Calvin-Xu** [comment]
So I tested again on both hardware, and it seems that on Apple hardware some (1 to 20) frames are initially dropped when switching, but then things return to normal as you describe. On my Hackintosh frames continue to get dropped as playback continues. Mpv's diagnostics show nothing unusual in the latter situation, except that 0 frames are dropped at the decoder and more and more frames are dropped at output.

I suppose the final variable I haven't been able to check is whether actual Apple hardware on Intel Integrated Graphics has this issue. However, I have not been able to force macOS to use iGPU when running Memento, and because no frames are dropped at the decoder I suppose that might not be the reason.

I wonder if you have a M1 MacBook Air. If you are testing on an Intel one, I apologize for causing much ado over nothing after all.

**Comment by ripose-jp** [comment]
>on Apple hardware some (1 to 20) frames are initially dropped when switching

You can expect about 7 or so frames to be dropped when loading any video. This is because a lot of work is being done when loading a video like parsing subtitle files, parsing track lists, updating the UI, etc. This happens on all platforms and isn't noticeable to anyone who isn't looking for it.

>On my Hackintosh frames continue to get dropped as playback continues.

This sounds like a driver issue, which is to be expected since things never seem to work right on Hackintoshes. Does your Hackintosh actually have GPU acceleration or is it emulating OpenGL in software? It may simply be a case of software rendering not being able to draw 24 FPS at the resolutions you're attempting to do so at.

>M1 MacBook Air

Yes I do. I'm unable to test bugs specific to Intel hardware, but there shouldn't be any.

**Comment by Calvin-Xu** [comment]
> Does your Hackintosh actually have GPU acceleration or is it emulating OpenGL in software?

Yes. There are actual Macs with HD630 so I'm using supported drivers on macOS 12.3.1. GPU acceleration works as far as I can tell, and also the stutter in fullscreen is gone as long as I have any of Memento's UI elements open in the main window as I reported (with the exception of the bottom OSD).

That said, this could definitely be a Hackintosh problem that doesn't impact other users. As long as it's not on actually Macs it's good. I'll try to get my hands on some Mac with just iGPU to test and if I can't reproduce the issue I'll close it.

**Comment by Calvin-Xu** [comment]
Didn't reproduce this on Mac with Iris Graphics 540, so probably some exotic Hackintosh problem.

**Comment by Calvin-Xu** [comment]
I just want to report some new experiences. I recently began using a 4K display for the Hackintosh system with HD630, and Memento playing the video in either (large) windowed or fullscreen mode has bad stutters; Making the window bigger than a certain size and drops begin to happen. I have found no obviously workaround.

Stock mpv and IINA are able to play the video smoothly, and I checked that this is not a recent regression. So I wonder if this might be a performance issue with Memento, visible here because I am on a very underpowered machine using a high resolution display.

**Comment by ripose-jp** [comment]
I'm interested to see if it's a problem with the single threaded rendering model. Can you test the version on the qml branch to see if it exhibits the same behavior? Word of warning, when fullscreening make sure to pause the video first or else your whole desktop may freeze up for about a minute or so.

**Comment by Calvin-Xu** [comment]
I am having some problems building the qml branch. Specifically right now:

```
CMake Error at CMakeLists.txt:37 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
```

**Comment by ripose-jp** [comment]
It's probably because it's an x86 machine. Try applying this diff.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2720409..9020bab 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,27 +1,89 @@
 cmake_minimum_required(VERSION 3.1.0)
-project(memento VERSION "0.5.0.1")
+
+set(MEMENTO_VERSION "0.5.6-beta")
+set(MEMENTO_SHORT_VERSION "0.5.6")
+execute_process(
+    COMMAND git log --pretty=format:'%h' -n 1
+    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
+    OUTPUT_VARIABLE MEMENTO_VERSION_HASH
+)
+
+if(APPLE)
+	project(Memento VERSION ${MEMENTO_SHORT_VERSION})
+else()
+	project(memento VERSION ${MEMENTO_SHORT_VERSION})
+endif()
 
 set(CMAKE_CXX_STANDARD 17)
 set(CMAKE_AUTOMOC ON)
 set(CMAKE_AUTORCC ON)
 set(CMAKE_AUTOUIC ON)
 
+# Set compiler flags
+set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCMAKE_VERSION='\"${MEMENTO_VERSION}\"'")
+set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
+set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DCMAKE_VERSION='\"${MEMENTO_VERSION}\"'")
+set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
+
+# Add the hash to the version if the RELEASE_BUILD flag isn't set
+if(NOT RELEASE_BUILD)
+	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DCMAKE_HASH='\"${MEMENTO_VERSION_HASH}\"'")
+	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCMAKE_HASH='\"${MEMENTO_VERSION_HASH}\"'")
+endif()
+
 if(APPIMAGE)
 	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DAPPIMAGE=1")
 	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DAPPIMAGE=1")
 endif()
 
-if(APPLE)
+if(APPBUNDLE)
+	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DAPPBUNDLE=1")
+	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DAPPBUNDLE=1")
+endif()
+
+# Sets the include directories to src
+# This isn't best CMake practice, but it produces the desired behavior of
+# setting include directories for all targets
+set(INCLUDE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/src")
+include_directories(${INCLUDE_DIRECTORY})
+
+if(APPLE AND NOT MAC_X86)
+	# This makes sure Memento builds on whatever arch is native
+	# The order of directories MATTERS because M1 users may crosscompile but
+	# x86_64 users will not
 	include_directories(
 		${CMAKE_INCLUDE_PATH}
 		${CMAKE_CURRENT_SOURCE_DIR}
 		${CMAKE_CURRENT_BINARY_DIR}
+
+		# arm64 locations
 		/opt/homebrew/include
 		/opt/homebrew/opt/qt5/include
+
+		# x86_64 locations
+		/usr/local/include
+		/usr/local/opt/qt5/include/
 	)
 
+	# x86_64 locations
+	list(PREPEND CMAKE_PREFIX_PATH /usr/local/opt)
+	list(PREPEND CMAKE_PREFIX_PATH /usr/local/)
+
+	# arm64 locations
 	list(PREPEND CMAKE_PREFIX_PATH /opt/homebrew/opt)
 	list(PREPEND CMAKE_PREFIX_PATH /opt/homebrew)
+elseif(APPLE AND MAC_X86)
+	# This is a crosscomile target, x86_64 users shouldn't need to use this
+	include_directories(
+		${CMAKE_INCLUDE_PATH}
+		${CMAKE_CURRENT_SOURCE_DIR}
+		${CMAKE_CURRENT_BINARY_DIR}
+		/usr/local/include
+		/usr/local/opt/qt5/include/
+	)
+
+	list(PREPEND CMAKE_PREFIX_PATH /usr/local/opt)
+	list(PREPEND CMAKE_PREFIX_PATH /usr/local/)
 else()
 	include_directories(
 		${CMAKE_INCLUDE_PATH}
@@ -32,19 +94,16 @@ endif()
 
 # Find Qt
 if(UNIX AND NOT APPLE)
-	find_package(Qt5 COMPONENTS Widgets Network Quick QuickWidgets Qml DBus REQUIRED)
-elseif(UNIX AND APPLE)
-	find_package(Qt5 COMPONENTS Widgets Network Quick QuickWidgets Qml REQUIRED)
+	find_package(Qt5 COMPONENTS QuickWidgets Widgets Network DBus X11Extras Svg REQUIRED)
+	include_directories(${Qt5Gui_PRIVATE_INCLUDE_DIRS})
+elseif(APPLE)
+	find_package(Qt5 COMPONENTS QuickWidgets Widgets Network Svg REQUIRED)
 elseif(WIN32)
-	find_package(Qt5 COMPONENTS Widgets Network Quick QuickWidgets Qml REQUIRED)
+	find_package(Qt5 COMPONENTS QuickWidgets Widgets Network Svg REQUIRED)
 endif()
 
 # Other dependencies
-if(APPLE)
-	set(MECAB "/opt/homebrew/lib/libmecab.dylib")
-else()
-	find_library(MECAB mecab)
-endif()
+find_library(MECAB mecab)
 find_library(SQLITE sqlite3)
 find_library(MPV_LIB mpv)
 find_library(JSONC json-c)
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 3d2343f..74c2a31 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -5,26 +5,137 @@ add_subdirectory(gui)
 add_subdirectory(anki)
 
 if(WIN32)
-	set(APP_ICON_RESOURCE_WINDOWS ../res/appicon.rc)
+	set(WINDOWS_APP_ICON_RESOURCE ../res/appicon.rc)
     set(WINDOWS_EXE_OPTION WIN32)
 endif()
 
-add_executable(
-    memento
-    ${WINDOWS_EXE_OPTION}
-    main.cpp
-    ../res/resources.qrc
-    ${APP_ICON_RESOURCE_WINDOWS}
-)
-target_link_libraries(
-	memento
-	mainwindow
-	Qt5::Qml
-)
+if(APPLE AND APPBUNDLE)
+	set(MACOS_ICON_FILE memento.icns)
+	set(MACOS_ICON_PATH ${PROJECT_SOURCE_DIR}/res/${MACOS_ICON_FILE})
 
+	add_executable(
+		${PROJECT_NAME}
+		MACOSX_BUNDLE
+		main.cpp
+		../res/resources.qrc
+		${MACOS_ICON_PATH}
+	)
+	set_target_properties(${PROJECT_NAME} PROPERTIES
+		BUNDLE True
+		MACOSX_BUNDLE_BUNDLE_NAME ${PROJECT_NAME}
+		MACOSX_BUNDLE_BUNDLE_VERSION ${MEMENTO_VERSION}
+		MACOSX_BUNDLE_COPYRIGHT "2020 - 2021 Ripose"
+		MACOSX_BUNDLE_GUI_IDENTIFIER "io.github.ripose-jp.memento"
+		MACOSX_BUNDLE_ICON_FILE ${MACOS_ICON_FILE}
+		MACOSX_BUNDLE_INFO_STRING "An mpv-based video player for studying Japanese"
+		MACOSX_BUNDLE_LONG_VERSION_STRING ${MEMENTO_VERSION}
+		MACOSX_BUNDLE_SHORT_VERSION_STRING ${MEMENTO_SHORT_VERSION}
+		MACOSX_BUNDLE_INFO_PLIST ${PROJECT_SOURCE_DIR}/macos/MementoInfo.plist.in
+		RESOURCE ${MACOS_ICON_PATH}
+	)
+
+	# Add in the dylibs
+	add_custom_command(
+		TARGET ${PROJECT_NAME}
+		POST_BUILD
+		COMMAND dylibbundler -od -b -x ./MacOS/Memento -d ./Frameworks -p @executable_path/../Frameworks
+		WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/src/${PROJECT_NAME}.app/Contents
+	)
+
+	# Manually add Python
+	# Get the path to vapoursynth-script
+	execute_process(
+		COMMAND ./getlib.sh ${MPV_LIB} vapoursynth-script
+		OUTPUT_VARIABLE OTOOL_VAPOURSYNTH_SCRIPT
+		WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}/macos
+	)
+	# Get the filename of vapoursynth-script mpv is linked to
+	string(REGEX MATCH "[^/]*$" VAPOURSYNTH_SCRIPT_NAME ${OTOOL_VAPOURSYNTH_SCRIPT})
+	# Get the otool path of Python vapoursynth-script is linked to
+	execute_process(
+		COMMAND ./getlib.sh ${OTOOL_VAPOURSYNTH_SCRIPT} Python
+		OUTPUT_VARIABLE OTOOL_PYTHON
+		WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}/macos
+	)
+	# Get the python framework paths
+	string(REGEX MATCH ".*Python\.framework" PYTHON_FRAMEWORK_PATH ${OTOOL_PYTHON})
+	# Get the path as it is in the appbundle
+	string(REGEX MATCH "Python\.framework.*" PYTHON_FRAMEWORK_END ${OTOOL_PYTHON})
+	# Change the path in vapoursynth-script
+	add_custom_command(
+		TARGET ${PROJECT_NAME}
+		POST_BUILD
+		COMMAND install_name_tool -change ${OTOOL_PYTHON} @executable_path/../Frameworks/${PYTHON_FRAMEWORK_END} ${VAPOURSYNTH_SCRIPT_NAME}
+		WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/src/${PROJECT_NAME}.app/Contents/Frameworks
+	)
+
+	# Run macdeployqt to pick up any plugins dylibbundler missed
+	if (MAC_X86)
+		set(MACDEPLOYQT_BIN "/usr/local/opt/qt5/bin/macdeployqt")
+	else()
+		set(MACDEPLOYQT_BIN macdeployqt)
+	endif()
+	add_custom_command(
+		TARGET ${PROJECT_NAME}
+		POST_BUILD
+		COMMAND ${MACDEPLOYQT_BIN} ${PROJECT_NAME}.app
+		WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/src
+	)
+
+	# Copy python. This need to happen here because Python confuses codesign
+	add_custom_command(
+		TARGET ${PROJECT_NAME}
+		POST_BUILD
+		COMMAND cp -RL ${PYTHON_FRAMEWORK_PATH} . && chmod -R 755 Python.framework
+		WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/src/${PROJECT_NAME}.app/Contents/Frameworks
+	)
+	add_custom_command(
+		TARGET ${PROJECT_NAME}
+		POST_BUILD
+		COMMAND rm -rf Current
+		WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/src/${PROJECT_NAME}.app/Contents/Frameworks/Python.framework/Versions
+	)
+	add_custom_command(
+		TARGET ${PROJECT_NAME}
+		POST_BUILD
+		COMMAND xattr -cr ${PROJECT_NAME}.app
+		WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/src
+	)
+
+	# Sign the code
+	add_custom_command(
+		TARGET ${PROJECT_NAME}
+		POST_BUILD
+		COMMAND codesign -s '${CERT}' --deep -f ${PROJECT_NAME}.app
+		WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/src
+	)
+else()
+	add_executable(
+		${PROJECT_NAME}
+		${WINDOWS_EXE_OPTION}
+		${WINDOWS_APP_ICON_RESOURCE}
+		main.cpp
+		../res/resources.qrc
+	)
+endif()
+target_link_libraries(${PROJECT_NAME} mainwindow Qt5::Svg)
+
+# This is a target that will create memento_debug.exe so that issues can be
+# debugged easier on Windows
+if(WIN32)
+	add_executable(
+		${PROJECT_NAME}_debug
+		${WINDOWS_APP_ICON_RESOURCE}
+		main.cpp
+		../res/resources.qrc
+	)
+	target_link_libraries(${PROJECT_NAME}_debug mainwindow Qt5::Svg)
+endif()
+
+# Install targets
 if(UNIX AND NOT APPLE)
 	install(
-		TARGETS memento
+		TARGETS ${PROJECT_NAME}
 		DESTINATION bin
 		COMPONENT binaries
 	)
diff --git a/src/gui/widgets/mpvframebuffer.cpp b/src/gui/widgets/mpvframebuffer.cpp
index b947264..6ddb5f5 100644
--- a/src/gui/widgets/mpvframebuffer.cpp
+++ b/src/gui/widgets/mpvframebuffer.cpp
@@ -65,7 +65,9 @@ QOpenGLFramebufferObject *MpvRenderer::createFramebufferObject(const QSize &size
         mpv_opengl_init_params gl_init_params{
             get_proc_address_mpv,
             nullptr,
+#if MPV_CLIENT_API_VERSION < 2
             nullptr
+#endif
         };
         mpv_render_param params[]{
             {MPV_RENDER_PARAM_API_TYPE, const_cast<char *>(MPV_RENDER_API_TYPE_OPENGL)},

```

**Comment by Calvin-Xu** [comment]
Thank you. I successfully built and ran the qml branch, and unfortunately performance appears identical to me.

I also tried applying the changes from https://github.com/ripose-jp/Memento/pull/33 seeing some of the warnings, which worked but had no effect on video playback framerate (or possibly made it worse because of my configuration).

**Comment by ripose-jp** [comment]
Unfortunately I can't say way the issue is. I know that IINA uses the OpenGL backend to render mpv, but that's where the similarities between Memento and IINA end. A lot of the OpenGL stuff is abstracted behind Qt, so once I render everything to the framebuffer, I don't really know what Qt does with it. I'd imagine the performance issues are within Qt since QML which does use off thread rendering for OpenGL, yet it still exhibits the same issues. I don't think I can fix this, much less really test it given the unique hardware you're using.

That said, if you find the problem, feel free to make a PR.
