### ISSUE TITLE
yomichan audio? 

### ISSUE THREAD

**Issue by djt311** [ripose-jp/Memento#11]
can't i play audio via yomichan inside memento?

**Comment by ripose-jp** [comment]
Assuming you're talking about this ![image](https://user-images.githubusercontent.com/72582120/117891270-76d75380-b26b-11eb-9bb2-065f6bd95450.png), there is no equivalent in Memento at the moment.

I can add it in a later release.

**Comment by ripose-jp** [comment]
![image](https://user-images.githubusercontent.com/72582120/121826305-ec1fb500-cc6b-11eb-99f8-c622cbbfd06f.png)
Added on dev
