### ISSUE TITLE
Change default directory for "Open file" 

### ISSUE THREAD

**Issue by twicepipes** [ripose-jp/Memento#110]
Every time Memento is restarted and the "Open file" option is chosen from the dropdown menu, it opens back up in the folder where the executable is located. It would be convenient if we could change this to a different directory via a configuration option so we don't have to navigate to our media directory every time the program is launched.

**Comment by ripose-jp** [comment]
I've added support for this on the dev branch. I'll merge it into master tonight or tomorrow.

If this is something that really bothers you, you should compile from source because there likely won't be a new Memento release until mpv v0.35 is released.
