### ISSUE TITLE
Regression: subtitlelist not populated with subtitle file

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#111]
Since 1053fa8f89c5cc4349639ea3615e6c02e66ad4f0, the subtitle list is not populated after a supported subtitle file is loaded; it falls back to the default behavior of adding new entries as they are shown during playback in mpv.

I tested with a local ASS file that has no parsing errors and worked for prior commits.

**Comment by ripose-jp** [comment]
I'm not able to reproduce this issue on macOS or Linux. I've tested both ASS and SRT files. Can you give me a subtitle file that has the problem you're describing?

**Comment by Calvin-Xu** [comment]
That is strange, every file I've tried so far does not seem to work.

Just saw the edit.

**Comment by ripose-jp** [comment]
I fixed the issue. I'll get it on master as soon as CI passes.

**Comment by Calvin-Xu** [comment]
No problem. I use Memento frequently and do my best to be specific. Thank you so much for your fast communication and fixes as always.
