### ISSUE TITLE
No subtitle recognition/no subtitles in subtitle list

### ISSUE THREAD

**Issue by squeakyrino** [ripose-jp/Memento#115]
I am trying to play an mkv file that has built-in subtitles and I can not seem to get the subtitle recognition (where it shows the definition on jisho) to work, even though the subtitles themselves work fine. The subtitles do not show up in the subtitle list either. I have also tried to manually add a subtitle file and the same happens, subtitles work fine but no recognition.

Now I have another anime which in mkv format with built-in subtitles and that one works fine, so I am wondering it it is some kind of issue with the file format itself or something.

I do not know exactly what info from the files I need to provide but I will keep an eye on the issue and let you know anything you need ASAP.

Thanks

**Comment by ripose-jp** [comment]
Memento doesn't work with raster subtitles. Make sure your subtitles are in a text-based format like SRT, VTT, or (usually) ASS.

**Comment by squeakyrino** [comment]
I did eventually try downloading subs from external websites and it worked. I don't know if there's a way to check if the mkv file has text subtitles and not raster subtitles but oh well, lesson learned.
