### ISSUE TITLE
Cursor disappears when in Fullscreen

### ISSUE THREAD

**Issue by Hirosashii** [ripose-jp/Memento#116]
Whenever I put Memento into fullscreen, the mouse cursor disappears which makes it hard to find where my mouse cursor actually is in the case when I want to hover over subs to define a word.

I tried messing with the parameters   --cursor-autohide=<number|no|always>   and   --cursor-autohide-fs-only

but to no avail.  Any way this is fixable?

**Comment by ripose-jp** [comment]
I'll need to add support for both those options.

**Comment by ripose-jp** [comment]
I've implemented support for both options on dev. I'll merge it into master after checks pass.

Support is disabled by default in favor of the current behavior that has the cursor hide and show along with the OSC. To enable it, you will have to go to **Behavior Settings** and uncheck 'Hide cursor with OSC".
