### ISSUE TITLE
Ability to include Second Subtitle Line from a few seconds ago to Anki Cards

### ISSUE THREAD

**Issue by Juiin** [ripose-jp/Memento#118]
I sometimes run into the Issue, that while the japanese subtitle line is still visible, technically the English(Second Subtitle) Line is not visible anymore and if i then try to make an Anki card, the second subtitle won't appear on my Anki card. Which i often don't notice until i review the Card in Anki, because i keep the Second Subtitles hidden most of the time. I don't know how Migaku mpv handles this on a technical level, but it feels like it still includes Second Subtitle Lines which where shown ~5-10 seconds earlier. 

This would avoid this issue, and i also find it useful to have the previous English(Second Subtitle) Sentence also on the Card for more Context. If the previous line appears right before the current one, it most of the time gives important context.

**Comment by ripose-jp** [comment]
The `{context-2}` marker will have the last secondary subtitle seen selected by default even if it is no longer on screen. I believe this does what you want. Close this if it does.

**Comment by Juiin** [comment]
This does work. Thanks for the answer. I still think it would be nice to have the option to include the last line from ~5-10 seconds ago for more context, but i'll close this.
