### ISSUE TITLE
Show Second Subtitles when hovering over the top quarter of the Video

### ISSUE THREAD

**Issue by Juiin** [ripose-jp/Memento#119]
Migaku mpv has this feature which is very convienent. It displays the second Subtitles at the Top of the Screen when you hover over it with you mouse. I'm not sure if it is possible technically to only display the Second Subtitles and not the Primary ones, since they would be duplicated with the ones from Memento, but even if it displays both, i still think it would be a nice feature. 

Basically Show Subtitles when your Mouse is over the top 25% of the Screen and Hide them otherwise, it would save me from using a hotkey.

**Comment by ripose-jp** [comment]
This will be possible when mpv 0.35 releases. Until then, mpv isn't capable of displaying primary and secondary subtitles independently.

**Comment by Juiin** [comment]
As i mentioned in the post, regardless of whether the primary subs are still visible or not, i still think this would be a great feature, if it is not too hard to implement.

Basically the way i used second subtitles with migaku mpv is to check my comprehension or check the english when i don't understand something. There i just need to hover over the top part of the screen, read the line, and move my mouse to hide the subs again. For me personally it would not matter if the primary subs become hard to read during this time, because they are displayed twice. That would just be polish.

**Comment by mansuen** [comment]
@ripose-jp now that mpv 0.35 has been released, is this enhancement considered for a future update? I think this would be very useful. I think that the secondary subtitles are sometimes distracting and it would be very convenient if they were hidden on default as they suggested. Thank you for developing Memento, it's an incredible application!

**Comment by ripose-jp** [comment]
It's completely possible and not particularly difficult to implement. Considering there is demand, I can bang it out some time soon. If you want though there's a script in #41 that will let you just toggle the secondary subtitle visibility with **Alt+v** without bringing up OSC text. You can also put `secondary-sub-visibility=no` in your `mpv.conf` to hide them by default.

Also I don't get notifications when someone reacts to a post, so I didn't know this one was popular.

**Comment by ripose-jp** [comment]
This has been implemented for both primary and secondary subtitles. I'll merge into master when I'm sure it works properly.
