### ISSUE TITLE
Second subtitle track feature not working on latest release (v0.4.6-alpha) on Windows 10

### ISSUE THREAD

**Issue by 97997** [ripose-jp/Memento#12]
What title says... I checked on the older version i had installed (v0.4.4-alpha) and the feature still works in that version. I haven't tested in linux.

**Comment by ripose-jp** [comment]
I'm not certain this is a bug exactly, but more of a trade off of having subtitles appear over the player.

If you want to use the second subtitle track, I recommend going to Settings -> Options -> Search and unchecking "Hide mpv subtitles when search bar is visible" and checking "Hide search bar when playing media".

**Comment by 97997** [comment]
Thanks a lot, it worked. 
Also I have the problem where I have some non-srt subtitles and those overlap the main subtitles track, i tried moving the subs with r/t but it moves both primary and secondary tracks, by any chance do you know a solution to this or a way to move subtitles tracks independently?

**Comment by ripose-jp** [comment]
Unfortunately that's a limitation of mpv, so I don't really have any control over it. My best guess is that the secondary subtitle track you're using is a bitmap.

From the mpv [docs](https://mpv.io/manual/master/#options-secondary-sid)
"There are some caveats associated with this feature. For example, bitmap subtitles will always be rendered in their usual position, so selecting a bitmap subtitle as secondary subtitle will result in overlapping subtitles."
