### ISSUE TITLE
could not add index.json (macOS)

### ISSUE THREAD

**Issue by activatedyeast** [ripose-jp/Memento#124]
Hello! Whenever I try and install a dictionary (I've tried all listed, including jmdict_english.zip), I simply get an error stating "could not add index.json"—unzipping the dictionaries doesn't change this error for me either. 

I've been trying to use it on macOS 12.0.

**Comment by ripose-jp** [comment]
I can't reproduce this using the latest version on macOS with the dictionaries linked in the README.

To add a dictionary you
1. Download a dictionary archive such as `jmdict_english.zip`
2. Open Memento
3. Open **Settings** → **Options** (**Memento** → **Preferences** on macOS)
4. Go to **Dictionaries**
5. Click the plus button
6. Open `jmdict_english.zip` which you downloaded earlier

Let me know if after following these exact steps it still isn't working for you.

**Comment by activatedyeast** [comment]
This is what I was doing originally, but after a clean install it seems to be working now. Thank you so much!

**Comment by ripose-jp** [comment]
Glad it's working. Since I can't reproduce this, I'll chalk it up to user error or a bad dictionary file.
