### ISSUE TITLE
Hovering the mouse dosen't always result into bar showing [not a bug]

### ISSUE THREAD

**Issue by OltiP2** [ripose-jp/Memento#125]
Turn this

(memento)

https://user-images.githubusercontent.com/97410429/196110072-adceb910-76c6-40e2-8114-5f39b6d3c6bf.mp4

to this (mpv)

https://user-images.githubusercontent.com/97410429/196103666-f628ce79-fa0a-438d-8d74-a35c0dbc9170.mp4

in mpv the bar only appears when you hover at the bottom of the screen

**Comment by ripose-jp** [comment]
I've explained my thoughts on this feature in #105

I'll leave this open so you can make a case for why this should be added.

**Comment by OltiP2** [comment]
It works perfectly, my issue was that when I brought my laptop into my bed and I had a mouse plugged in if I moved just a bit the OSC appeared and that happened very frequently, it wasn't just a distraction but also covered the video, it's not so much of a necessity now since I'm able to toggle it on/off or auto (press del to change)
also sorry for making another duplicate

**Comment by ripose-jp** [comment]
I'm closing this because there hasn't been any activity for a week. Feel free to reopen this if you have something to say with regard to my last suggestion not working for you.
