### ISSUE TITLE
"Show in anki" button doesn't show up

### ISSUE THREAD

**Issue by Neggedah** [ripose-jp/Memento#127]
be36ac9367276048a43b0941afcc994c29996e35 fixed the problem I mentioned in #126 in the title, but not the other one I mentioned in the body.
The "Show in anki" button still doesn't show up if the term was added as the reading, unless you have just added it and have not closed the definition window yet. But it doesn't appear if you hover over the same term again after having closed the definition window you have just added the card in.

**Comment by ripose-jp** [comment]
Sorry I closed the last issue without fixing the second one. I just skimmed the issue since I got the idea of what is was from the title and immediately knew that could happen given the implementation.
