### ISSUE TITLE
Blackscreen when exiting fullscreen

### ISSUE THREAD

**Issue by tarkan3d** [ripose-jp/Memento#129]
When doubleclicking or pressing F to exit fullscreen my entire screen turns black and I can't see neither Memento UI nor Windows UI. However, by pressing spacebar or rightclicking the video seems to continue playing (you can hear audio), but the screen remains black. I need to exit Memento by pressing Escape first before I can see anything on my screen again.
Interestingly enough when trying to tab into another window my screen remains black, but it seems that both keyboard and mouse input are still recognized.

This issue doesn't seem to occur when activating Menu Bar - 'Enable in fullscreen (Not Recommended)'. However It'd be nice if I wouldn't have to activate this setting since the pixel border is taking away a bit from the viewing experience.

Windows 10
Memento version 0.5.6-beta-662e562

**Comment by ripose-jp** [comment]
Everything you've described is a dead ringer for bugs in your graphics drivers. I've seen similar problems with #48, so please make sure you are on the latest version.

**Comment by tarkan3d** [comment]
Thanks, this actually did solve the issue!
