### ISSUE TITLE
Showing timestamp 

### ISSUE THREAD

**Issue by djt311** [ripose-jp/Memento#13]
add the option to show timestamp on the left subtitles list visibility.  
![image](https://user-images.githubusercontent.com/84034286/118410502-0461db80-b690-11eb-8d00-16185c2b6156.png)

**Comment by ripose-jp** [comment]
I forgot to mention that in the meantime, you can seek to any subtitle in the list by double clicking it.

**Comment by ripose-jp** [comment]
![image](https://user-images.githubusercontent.com/72582120/120048164-3ac22380-bfcb-11eb-9b43-4ba4776c3a02.png)
Added on the dev branch.
