### ISSUE TITLE
Command line arguments don't work from AppImage

### ISSUE THREAD

**Issue by cessen** [ripose-jp/Memento#130]
(First of all: thanks so much for building and maintaining this awesome tool!)

I usually start video players like mpv from either the command line directly, or via scripts hooked up to custom menus in my file browser.  However, the AppImage build of Memento seems to ignore any command line arguments passed to it.  For example:

```sh
$ Memento_Linux_x86_64.AppImage path/to/some/video.mkv
```

Just launches Memento with no file loaded, whereas I would expect it to launch and play the passed file.  This isn't a deal breaker or anything, since I can just drag files/folders into memento instead.  But it does make things a little awkward.

**Comment by ripose-jp** [comment]
I hate to say this, but it works on my machine. Do you have `xdg-open` installed?

**Comment by cessen** [comment]
Gah!  This was my bad.  The combination of there being no `--help` and things not working when I was passing file paths inside a shell script made me think no arguments were getting through.

Turns out they *were* getting through, but I was passing them via `$@` instead of `"$@"`, which made files with spaces in the names not work (through no fault of Memento).

You might consider adding a minimal `--help` response, where it just prints a message and exits.  I&mdash;and I suspect others&mdash;use that not only to get help but also to check if the software is responding correctly from the command line.

Anyway, sorry for the false report!
