### ISSUE TITLE
Where can I donate to financially support this project?

### ISSUE THREAD

**Issue by zoro11031** [ripose-jp/Memento#131]
Memento is the best solution I've found to making anime subtitles on Linux. I used to use Migaku and it was extremely janky. I would like to donate to show appreciation and also hopefully make sure this project doesn't die

**Comment by ripose-jp** [comment]
I don't accept money to work on Memento. The amount of money you would need to donate to "make sure this project doesn't die" is in the six figure range.

If you have extra money to spend, considering donating it to the [EFF](https://www.eff.org/) or [FSF](https://www.fsf.org/).
