### ISSUE TITLE
Create a card using the kana reading of a word

### ISSUE THREAD

**Issue by pattontj** [ripose-jp/Memento#132]
Similar to yomichan, I would like to see a similar feature that allows for card creations using only the kana reading of the dictionary entry. This would be particularity useful when creating cards that are usually written using kana alone, and be a discretionary option for those that want it.
![image](https://user-images.githubusercontent.com/60120527/201446990-35ffe709-db9d-4aa4-9972-645b7288ec81.png)

**Comment by ripose-jp** [comment]
Already implemented #114
