### ISSUE TITLE
[Feature request] Frequency data in definitions

### ISSUE THREAD

**Issue by zoro11031** [ripose-jp/Memento#134]
There are some implementations of Anki dictionaries that allow you to import frequency data for words, and then append them to definitions. For example the legacy version of [the Migaku addon](https://github.com/migaku-official/Migaku-Dictionary-Addon). 

Would it be possible to implement this feature? I find it very helpful with prioritizing which words to actually add in to my main deck and study, and I think others would too. For reference here is what the Migaku dictionary implementation looks like (the stars are 1-5 and indicate frequency): 

【灼熱】 しゃくねつ ★★
becoming red hot, red heat, scorching heat, incandescence

Admittedly this is a bit of a selfish feature request, the legacy Migaku Dictionary is no longer supported or updated and has been deprecated in favor of a closed source subscription model that relies on using Chromium; if this feature were implemented I could just get rid of it from my workflow entirely.

**Comment by ripose-jp** [comment]
I'm not sure I understand the feature request.

>Anki dictionaries

I don't know what you mean by this. Are you referring to Yomichan dictionaries or Anki cards?

If you're trying to add something like 【灼熱】 しゃくねつ ★★ to a note, couldn't you just use
```
【{expression}】 {reading} {frequencies}
```
with only one frequency dictionary that uses stars enabled?

**Comment by zoro11031** [comment]
My bad man, you're right. I completely forgot that Yomichan supports dictionaries with frequency enabled. I'll go ahead and close this, sorry for wasting your time.
