### ISSUE TITLE
audio padding settings arent saved on exit

### ISSUE THREAD

**Issue by TingTingin** [ripose-jp/Memento#14]
when using the app and setting the audio padding on reopen the settings are reset to their default paddings

**Comment by TingTingin** [comment]
actually seems like it was my mistake the folder it was in apparently needed admin rights so when i run the app with admin rights it seems to work properly

**Comment by ripose-jp** [comment]
The only reason you would need to run Memento as an administrator is because the ```config``` folder is in a write protected area like ```Program Files```.

If running Memento as administrator doesn't bother you, you can keep it there I guess.

**Comment by TingTingin** [comment]
yeah eventually realized it was all the settings that weren't saving unless admin anyway

Another issue I noticed is that in the Anki export settings if you put in Japanese characters in the template like 音読み it doesn't save properly it can add the card to Anki with the Japanese characters if you leave memento open but when you restart memento the Japanese characters are replaced with ??? instead of 音読み

**Comment by ripose-jp** [comment]
That's definitely a text encoding issue during reading or writing the anki_connect.json file. Probably the writing portion if I had to guess just by looking at the code. Windows is a pain about that sort of stuff. That's a separate issue from this one though.

I'll be sure to fix it in the next release.
