### ISSUE TITLE
MacOS - Please ensure your Linux system has 64 bit binary support

### ISSUE THREAD

**Issue by Roxiun** [ripose-jp/Memento#140]
Version v1.0.0
OS: macOS 13.1 (M1 Macbook Air)

When attempting to add a word to anki, I get an error saying "Please ensure your Linux system has 64 bit binary support."
<img width="1373" alt="Screenshot 2022-12-31 at 5 52 30 am" src="https://user-images.githubusercontent.com/31913075/210114021-7060f7ab-7114-4fe4-8092-8d50d22f1426.png">

**Comment by ripose-jp** [comment]
That error message doesn't exist anywhere in my source code, but that exact message exists [here](https://github.com/obynio/anki-japanese-furigana/blob/master/reading.py#L205). That error is being sent back from AnkiConnect and all Memento does is display it. I recommend you report this bug to their repository.

**Comment by Roxiun** [comment]
Alright thanks, will do

**Comment by Roxiun** [comment]
Installing Rosetta fixed the problem
