### ISSUE TITLE
Changing font size for secondary subtitle track

### ISSUE THREAD

**Issue by Mahiinaa** [ripose-jp/Memento#147]
Hello thank you for creating this program. 

It's pretty straightforward to change the font size of the primary subtitle track but how would I go about doing that for the secondary track?

**Comment by ripose-jp** [comment]
The secondary subtitle is handled by mpv and customization of it is extremely limited. The code changes required to enable this functionality in mpv are trivial, but avih is opposed to hacking additional functionality into secondary subtitles any further. I'm not willing to undertake of full rewrite of mpv's subtitle backend and I'm also not willing to fight them on something like this.

Here's a link to pull request if you want further insight into the issues with secondary subtitles in mpv
https://github.com/mpv-player/mpv/pull/8954
