### ISSUE TITLE
Unpause video when cursor is away from subtitles

### ISSUE THREAD

**Issue by ayseru** [ripose-jp/Memento#150]
Ever since the last update, automatically pausing on hover has been very useful. One more way I can think of to increase efficiency could be to automatically unpause on hover, this would remove the need to manually unpause, reducing one less input.

This feature that exists from the Chrome extension Language Reactor. If possible, I wish that something similar could be implemented into Memento.

Currently, subtitles show when the cursor is in the bottom 20% of the player. A problem I have found with this idea could be that it prevents Anki mining or scrolling through the pop-up.

One suggestion I can make is that the player unpauses only when there are no popup windows present. For this to remain inputless, another suggestion I can make is when the cursor enters then exits the dictionary pop-up, it will automatically be hidden, a feature that exists on Yomichan. The user could simply just swipe their cursor upwards from the currently hovered word, through the pop-up, and the player would then unpause, thus allowing for a seamless lookup process without any button inputs.

I have zero coding experience, so I have no idea of what the limitations are. If it is not possible to implement, feel free to dismiss this idea.

**Comment by ripose-jp** [comment]
>automatically unpause on hover

This feature doesn't work for anyone that needs to move their mouse off search results to interact with other elements like the subtitle list. This basically makes all `{context}` markers unusable.

>This feature that exists from the Chrome extension Language Reactor.

I've seen a few people use this as a justification for why a feature should be in Memento. I'm not competing with them. What choices they make for their software don't affect Memento in any way.

>another suggestion I can make is when the cursor enters then exits the dictionary pop-up, it will automatically be hidden

I did this back when Memento was barely a few weeks old and it was terrible. If you accidentally moved your mouse outside the popup, the whole thing would disappear and you would lose your place. It is exceptionally hard to close the popup accidentally now, as it should be.

>Currently, subtitles show when the cursor is in the bottom 20% of the player. A problem I have found with this idea could be that it prevents Anki mining or scrolling through the pop-up.

This is not a problem, I thought of this and implemented a solution before I pushed the feature.

I'm not big on this feature. If anything, one of Memento's biggest issues is its reliance on the mouse. With mpv you never have to use the mouse. The entire player can be controlled with the keyboard. That's the direction Memento should be moving in.

**Comment by ripose-jp** [comment]
Closing this as a wontfix since there's been no response for a week.

**Comment by Calvin-Xu** [comment]
> automatically unpause on hover

I recall one fork did this feature. You can look  for it and possibly rebase it to your local build. But I don’t remember it worked very well in actual usage.

**Comment by ripose-jp** [comment]
I originally took the idea of the auto-pause feature from mdatsev's fork. I didn't look at his code, just the commit message, so I don't know if he implemented it in such a way that it unpaused after moving the cursor off of the subtitles.
