### ISSUE TITLE
Modifier keys don't behave correctly on macOS

### ISSUE THREAD

**Issue by NonVoxPopuli** [ripose-jp/Memento#153]
The modifier keys on macOS don't interact with mpv as expected and in some cases are broken. If you launch Memento from the command line you can see the normal output mpv would produce, including how mpv interprets the input keys. 
Command reads as Control and vice versa, Control (reading as Meta) doesn't combine with any other key to produce an output, and Alt reads along with it's corresponding alt code.
• ⌃
sends 'Meta+' (not Ctrl) and nothing else, regardless of what key is pressed. 
mpv always returns: "Meta+ is not a valid input name."

• ⌥ 
sends 'Alt+(alt code)' 
So the keys 'Alt+2' send 'Alt+™' and 'Alt+8' send 'Alt+•' (Alt plus their corresponding Apple alt code) 

• ⌘ 
sends 'Ctrl+(key)' (not Meta)

For ⌘ and ⌃ the [documentation notes](https://doc.qt.io/qtforpython-5/PySide2/QtCore/Qt.html#PySide2.QtCore.PySide2.QtCore.Qt.KeyboardModifier) these keys are bound backwards on mac. As for Alt, I don't know how mpv usually interprets them to stop from reading the Apple Alt code.
The issue also appears to be limited only to mpv's input, because the other keyboard commands, like ⌘O to open a file, work just fine.
I've tried to go searching for how to fix the Meta key not registering with any other inputs, but I can't figure out why it would be registering any differently than any of the other modifier keys that all seem to work correctly.

**Comment by Calvin-Xu** [comment]
I ran into this with https://github.com/ripose-jp/Memento/issues/67. I feel doing something here might be promising: https://github.com/ripose-jp/Memento/blob/cfa59f05be44538d9bc47e482cce0adf74498184/src/player/mpvadapter.cpp#L1012

I only have simple keybinds and just set `Ctrl+c ignore`.

**Comment by ripose-jp** [comment]
I was able to fix the `Meta+` issue and Option/Alt binds sending weird symbols. I won't be swapping modifier keys on macOS since they've been the way they are for years. I see no reason to change them just because there's a more "correct" way to map Apple's weird modifiers to standard modifiers.

**Comment by NonVoxPopuli** [comment]
For anyone who finds this in the future. I was able to work around Apple's weird naming scheme by doing the following.

1.  `cd  ~/Library/Preferences/memento` then `cp -r ~/.config/mpv/* ~/Library/Preferences/memento/`
   to copy your mpv configs over to memento.
2. `grep -rinE 'ctrl|meta|super' --color=always` to list everywhere ctrl, meta, or super is used.
  You can add `-l` to the end to just get a list of only file names.
3. `gsed  -i ' s/[cC][tT][rR][lL]/CTRl/g;
        s/[mM][eE][tT][aA]/METa/g;
        s/[sS][uU][pP][eE][rR]/SUPEr/g;
s/CTRl/META/g; s/METa/CTRL/g; s/SUPEr/CTRL/g' <your file here>`
  - This will replace **every** case-insensitive instance of the words **"meta"**, **"ctrl"**, and **"super"**.
    if those words are used anywhere else in that file as variables this _will_ mess them up and you will
    have to fix it manually. If the only file you're running this on is `input.conf` you should be fine.
  - macOS's internal `sed` didn't like this command very much from me so I had to use `gsed` or gnu's version
    of sed. You can install it with `brew install coreutils`.
