### ISSUE TITLE
Looking up Bug

### ISSUE THREAD

**Issue by OltiP2** [ripose-jp/Memento#158]
https://user-images.githubusercontent.com/97410429/235080593-01a5eaf0-67e0-4079-8323-06db54792f99.mp4

**Comment by ripose-jp** [comment]
It looks like you're searching the （ character by accident. If you select it, you can see its much wider than it looks. Your subtitles are also quite big, so a 250ms search delay doesn't seem to work for you anymore. I'd recommend either switching to modifier search, increasing the delay, or making your subtitles smaller.

Doesn't look like a bug from what I can tell though.

**Comment by OltiP2** [comment]
My search delay was actually at 0ms so i switched it to 250ms now it works.
