### ISSUE TITLE
Furigana-plain gives hirgana

### ISSUE THREAD

**Issue by hgoelen** [ripose-jp/Memento#163]
Hello,

When adding cards, I noticed the program was not detecting duplicates as such. I have my duplicate field set to VocabFurigana and I used the {furigana-plain} expression to fill in that field, so for example 彼女[かのじょ]. However, when adding a card for 彼女, the field VocabFurigana gets filled with just かのじょ. {furigana} does seem to work as intended. Is this a known issue? I am on Windows 11.

Thanks in advance.

**Comment by ripose-jp** [comment]
In version 1.1.0 duplicate behavior was changed in response to #151. You probably already have 彼女 as a kanji card in your deck. In this case Memento will still give you the ability to add the hiragana reading even if it detects that kanji card. That sounds like what you're dealing with.

If you ever see the hamburger button, it detected a duplicate.
![image](https://github.com/ripose-jp/Memento/assets/72582120/1dd41c8b-6098-4abe-b9e7-ecb4e3e1b619)

**Comment by hgoelen** [comment]
You're right, thanks!
