### ISSUE TITLE
Option for an alternate frequency output

### ISSUE THREAD

**Issue by pedipanol** [ripose-jp/Memento#164]
I use a frequency sorting setup by Marv that involves a handlebar in yomichan to remove the dictionary name of the output and output only the highest priority dictionary's value (and adds a 999999 value if no frequency is found). With this all new words in Anki will be the ones you mined that have the highest frequency within the dictionary you're using.

https://github.com/MarvNC/JP-Resources#sorting-mined-anki-cards-by-frequency

 For now I just backfill them later, but an option for Memento to do that natively would be awesome.

That's pretty much the only nitpick I've had in using the program in the past week, keep up the great work!

**Comment by ripose-jp** [comment]
While there is a request for Handlebar support #79 and it is possible to implement via MuJS, the effort it would take to implement versus the benefit it would add is too small for me to really be too be interested at the moment. If this were to get implemented, I'd rather be through the extended marker syntax idea kicked around in #143.

Just to make sure I understand correctly, you want to only add the value of the first frequency dictionary without the name?

**Comment by pedipanol** [comment]
Yeah, it doesn't need to be a full implementation of the handlebar, if it can output just the first dicionary's value it would be enough for me!

**Comment by snfergy** [comment]
Is this still being considered?

**Comment by BigBoyBarney** [comment]
> I use a frequency sorting setup by Marv that involves a handlebar in yomichan to remove the dictionary name of the output and output only the highest priority dictionary's value (and adds a 999999 value if no frequency is found). With this all new words in Anki will be the ones you mined that have the highest frequency within the dictionary you're using.


I had this exact issue, which I mentioned in #202 as well. 
As a temporary solution, I wrote a quick Anki add-on to trim your frequency field to the lowest value. 
https://codeberg.org/Sylphrena/AnkiFieldTrimmer
It essentially mimics what the handlebars do in yomichan.

**Comment by pedipanol** [comment]
Closing this now that I see the problem has been solved by the new frequency markers being supported thanks to #238 (not on main build yet)

Support for the other Yomitan markers would be cool too
