### ISSUE TITLE
Auto download jap subtitles with yt-dlp for youtube videos

### ISSUE THREAD

**Issue by bakustarver** [ripose-jp/Memento#167]
Could you add an automatic Japanese subtitle download function using yt-dlp or the [youtube-transcript](https://github.com/jdepoix/youtube-transcript-api) ?

with the command line

$ memento https://youtube.com/watch?v=jTW30Ht1o8o
The video is loading but without the Japanese subtitles

it would be good to have a button in player and the command line
This will be a useful feature for the program

**Comment by ripose-jp** [comment]
#61
