### ISSUE TITLE
SubtitleParser acceptable encodings?

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#170]
I had a subtitle file in UTF-16 LE (SRT), and the parser fails immediately at the leading position (SRT Parser: Invalid position "��1"). Since mpv accepts subtitles in this encoding with no problem, maybe this can be addressed?

Also, may I suggest also printing the line number where it encounters an error in addition to printing the line out to help the user locate and fix the subtitle file?

**Comment by ripose-jp** [comment]
Could you link me to an SRT file that does this?

>Also, may I suggest also printing the line number where it encounters an error in addition to printing the line out to help the user locate and fix the subtitle file?

This probably won't be difficult, but I'll have to check when I fix this.

**Comment by Calvin-Xu** [comment]
This one does it on latest built of master. It's not the original problematic one; I just converted it back to UTF-16 LE

[Patlabor_the_Movie_(1989)_[720p,BluRay,x264]_-_THORA.txt](https://github.com/ripose-jp/Memento/files/12075030/Patlabor_the_Movie_.1989._.720p.BluRay.x264._-_THORA.txt)

> This probably won't be difficult, but I'll have to check when I fix this.

Thanks. I just added a counter for tracking down this issue. Should not be too bad.
