### ISSUE TITLE
Have option to remove duplicate definitions when adding a card

### ISSUE THREAD

**Issue by ghost** [ripose-jp/Memento#175]

**Comment by ripose-jp** [comment]
I need you to layout more information on how you'd like this to work.
Do you want higher priority dictionaries to cancel out definitions from lower priority ones?
How do you want to them to match? Entire matching lines only?
Do you want it always enabled or only sometimes?

**Comment by OltiP2** [comment]
> Do you want higher priority dictionaries to cancel out definitions from lower priority ones?

yes

> How do you want to them to match? Entire matching lines only? 

yes

> Do you want it always enabled or only sometimes? 

I think an option to enable it or disable it would be nice (always or not)
