### ISSUE TITLE
Option to select a single definition

### ISSUE THREAD

**Issue by ElaxDev** [ripose-jp/Memento#179]
I think it would be good to have the option to select a single definition easier, because I have multiple dictionaries and when I'm going to mine a word I select the best definition and then I have to go one by one deselecting the other definitions, it could be done that if you double click the checkmark of a definition the other ones deselect and only that one is selected or to have an option to have all the definitions deselected by default and then just select the one you want to mine.

**Comment by ripose-jp** [comment]
Already implemented in #53. Go to **Settings** → **Options** → **Anki Integration** → Tick **Show Advanced Options** → **Include In Glossary**.
