### ISSUE TITLE
Character isn't highlighted if the cursor is on the right side of a character

### ISSUE THREAD

**Issue by eshrh** [ripose-jp/Memento#18]
Currently, if your cursor is in the right ~60% of a certain glyph, that glyph isn't highlighted and looked up. Here's a short [video](https://streamable.com/b8j4nd) to explain what I mean.

I think this is an important thing to change because of how central the text selection is to the program. Currently the most reliable way to select a word is to move the cursor to the very left of the character, or the gap between the character and the next one to the left. You should be able to move your cursor directly *to* the character, this is how yomichan works on the browser: when the cursor is even slightly on the next glyph, it's selected. 

I think this is different to latin-script highlighting, where the current behavior makes sense; characters are much more discrete in CJK.

I know this is really nitpicky, so if this is a can't-fix or is just too much work then please close the issue.

**Comment by ripose-jp** [comment]
I honestly thought this was unfixable for the longest time, so I ignored it. I just found a forum post about a different Qt method for calculating what character the cursor is over and it finally works properly.

The fix is on master.
