### ISSUE TITLE
Error when building 1.2.1 in Debian (Ubuntu).

### ISSUE THREAD

**Issue by AxillV** [ripose-jp/Memento#182]
My guess would be that there is something funky going on with the provided versions of mpv and it's libraries?

Here is the cmake output:
[ 44%] Linking CXX static library libhittestwidget.a
[ 45%] Building CXX object src/gui/widgets/mpv/CMakeFiles/mpvwidget.dir/mpvwidget.cpp.o
[ 46%] Building CXX object src/gui/widgets/mpv/CMakeFiles/mpvwidget.dir/mpvtimer.cpp.o
[ 46%] Building CXX object src/gui/widgets/mpv/CMakeFiles/mpvwidget.dir/mpvwidget_autogen/mocs_compilation.cpp.o
[ 47%] Building CXX object src/gui/widgets/mpv/CMakeFiles/mpvwidget.dir/osctimer.cpp.o
gmake[3]: Leaving directory '/home/user/MementoSource/build'
[ 47%] Built target hittestwidget
[ 48%] Linking CXX static library libstrokelabel.a
gmake[3]: Leaving directory '/home/user/MementoSource/build'
[ 48%] Built target strokelabel
**/home/user/MementoSource/src/gui/widgets/mpv/mpvwidget.cpp:35:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
   35 | #include <qpa/qplatformnativeinterface.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~**
**compilation terminated.
gmake[3]: *** [src/gui/widgets/mpv/CMakeFiles/mpvwidget.dir/build.make:104: src/gui/widgets/mpv/CMakeFiles/mpvwidget.dir/mpvwidget.cpp.o] Error 1**
gmake[3]: *** Waiting for unfinished jobs....
[ 49%] Linking CXX static library libutils.a
gmake[3]: Leaving directory '/home/user/MementoSource/build'
[ 49%] Built target utils
gmake[3]: Entering directory '/home/user/MementoSource/build'
gmake[3]: Leaving directory '/home/user/MementoSource/build'
gmake[3]: Entering directory '/home/user/MementoSource/build'
[ 50%] Automatic MOC and UIC for target audioplayer
gmake[3]: Leaving directory '/home/user/MementoSource/build'
[ 50%] Built target audioplayer_autogen
gmake[3]: Entering directory '/home/user/MementoSource/build'
gmake[3]: Leaving directory '/home/user/MementoSource/build'
gmake[3]: Entering directory '/home/user/MementoSource/build'
[ 51%] Building CXX object src/audio/CMakeFiles/audioplayer.dir/audioplayer_autogen/mocs_compilation.cpp.o
[ 51%] Building CXX object src/audio/CMakeFiles/audioplayer.dir/audioplayer.cpp.o
[ 52%] Linking CXX static library libsubtitleparser.a
gmake[3]: Leaving directory '/home/user/MementoSource/build'
[ 52%] Built target subtitleparser
gmake[3]: Entering directory '/home/user/MementoSource/build'
gmake[3]: Leaving directory '/home/user/MementoSource/build'
gmake[3]: Entering directory '/home/user/MementoSource/build'
[ 53%] Automatic MOC and UIC for target subtitlelist
gmake[3]: Leaving directory '/home/user/MementoSource/build'
[ 53%] Built target subtitlelist_autogen
gmake[3]: Entering directory '/home/user/MementoSource/build'
gmake[3]: Leaving directory '/home/user/MementoSource/build'
gmake[3]: Entering directory '/home/user/MementoSource/build'
[ 54%] Building CXX object src/gui/widgets/CMakeFiles/subtitlelist.dir/subtitlelist_autogen/mocs_compilation.cpp.o
[ 55%] Building CXX object src/gui/widgets/CMakeFiles/subtitlelist.dir/subtitlelistwidget.cpp.o
gmake[3]: Leaving directory '/home/user/MementoSource/build'
**gmake[2]: *** [CMakeFiles/Makefile2:1413: src/gui/widgets/mpv/CMakeFiles/mpvwidget.dir/all] Error 2**
gmake[2]: *** Waiting for unfinished jobs....
[ 55%] Linking CXX static library libdictionary_db.a
gmake[3]: Leaving directory '/home/user/MementoSource/build'
[ 55%] Built target dictionary_db
[ 56%] Linking CXX static library libaudioplayer.a
gmake[3]: Leaving directory '/home/user/MementoSource/build'
[ 56%] Built target audioplayer
[ 57%] Linking CXX static library libflowlayout.a
gmake[3]: Leaving directory '/home/user/MementoSource/build'
[ 57%] Built target flowlayout
[ 57%] Linking CXX static library libsubtitlelist.a
gmake[3]: Leaving directory '/home/user/MementoSource/build'
[ 57%] Built target subtitlelist
**gmake[2]: Leaving directory '/home/user/MementoSource/build'
gmake[1]: *** [Makefile:136: all] Error 2
gmake[1]: Leaving directory '/home/user/MementoSource/build'
make: *** [Makefile:4: release] Error 2**

**Comment by ripose-jp** [comment]
You're missing the private Qt headers. RHEL and Debian like to separate them out into their own packages for some reason. Install the `qtbase5-private-dev` package.
