### ISSUE TITLE
Add only the highlighted text as glossary

### ISSUE THREAD

**Issue by basketweavr** [ripose-jp/Memento#184]
I'm not sure if this feature has been requested previously, didn't find anything with a quick search. 
For words with multiple meanings in installed dictionaries, I'd like to be able to only add one or two of the meanings by selecting them in the dictionary hover menu. Eg:

![image](https://github.com/ripose-jp/Memento/assets/147221098/3fbc4ece-2706-4b97-bbd4-be8972c318c8)

So highlighting "to pass through | to pass by" would only add those two as the glossary for the Anki entry, instead of me needing to manually edit the created card and removing the rest of it. It also would be faster to add particular definitions for words with multiple meanings than having to uncheck several definitions in the dictionary entry.

**Comment by ripose-jp** [comment]
I don't think this a problem to be solved on Memento's side. This is a problem with dictionary formatting, assuming you consider a problem to begin with. I also don't think it's an intuitive feature as it isn't clear that selecting text in a dictionary entry will truncate the entry when adding a card.

I'm going to have to reject this one.
