### ISSUE TITLE
Heads up for those using Anki flatpak

### ISSUE THREAD

**Issue by koalagang** [ripose-jp/Memento#189]
I use personally use nix and had no issue but I was helping my brother (who uses flatpak) set up memento and had issues getting the screenshots and audio added to his cards. After investigating on his system for a bit, I realised that memento creates its screenshots and audio clips in `/tmp` -- a directory which the [Anki flatpak](https://flathub.org/apps/net.ankiweb.Anki) sandbox does not have access to by default. I fixed the issue by giving Anki access to the `/tmp` directory. This can easily be done with [flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) -- a graphical utility for reviewing and modifying the permissions of your flatpak applications.

I would suggest adding a note about this to the README.

**Comment by ripose-jp** [comment]
Thanks for the heads up. I'll add something to the troubleshooting section of the README. I'll look into sending images and audio as base64 so hopefully this sort of thing becomes a non-issue.
