### ISSUE TITLE
Is there a way to make the word on popup bigger? 

### ISSUE THREAD

**Issue by kjgbkvhlvfiykfvil** [ripose-jp/Memento#197]
In Yomichan you can edit it like this:
.source-text {
    font-size: 17px;
}

**Comment by ripose-jp** [comment]
Unfortunately those can't be changed with stylesheets and are hard coded. You'll have to edit these [lines](https://github.com/ripose-jp/Memento/blob/c50b7bfe4d72c8b1fc91811ed4aa06c451be6690/src/gui/widgets/definition/termwidget.cpp#L66) and recompile.

**Comment by kjgbkvhlvfiykfvil** [comment]
Thanks, I was able to build it, even if it took me a while since I don't have experience in building from source. Although I still don't know what is Json-C. Is there a way to make popup smaller, remove popup's border, make tags smaller and have compact tags like on Yomichan?

**Comment by ripose-jp** [comment]
>make popup smaller

[Change these numbers.](https://github.com/ripose-jp/Memento/blob/master/src/gui/widgets/definition/definitionwidget.ui#L9)

>remove popup's border

[Change this to `QFrame::NoFrame`.](https://github.com/ripose-jp/Memento/blob/master/src/gui/widgets/definition/definitionwidget.ui#L81)

>make tags smaller

Go to **Settings** → **Options** → **Interface**. Check **Enable custom style sheets**, go to **Definitions**, and change the font size.

>have compact tags like on Yomichan

Apply this [patch](https://github.com/ripose-jp/Memento/files/9621252/sameline.txt).

**Comment by kjgbkvhlvfiykfvil** [comment]
I don't think patch worked. Isn't font size in Definitions for general glossary font size, not just tags?

**Comment by kjgbkvhlvfiykfvil** [comment]
Also what should I do if it doesn't play hevc videos smoothly? Do I have to install codec support additionally? Videos play normally on PotPlayer

**Comment by ripose-jp** [comment]
>I don't think patch worked.

It still works on the latest commit. It'll look like this if it worked:
![image](https://github.com/ripose-jp/Memento/assets/72582120/033a73f7-134a-433e-8f5d-1b8acf5c5127)

>Definitions for general glossary font size, not just tags?

It affects both. If you want it to only affect tags, only apply it to the `QLabel`s and not to `QTextEdit`s. It works the same as standard CSS syntax.

>Also what should I do if it doesn't play hevc videos smoothly? 

What is your OS, graphics card, and CPU?
Try updating your graphics driver first.
Try enabling hardware decoding with `ctrl+h`. If this fixes it, you can add `hwdec=auto` to your `mpv.conf`, though be warned that hardware decoding can be buggy.

>Do I have to install codec support additionally?

No. HEVC wouldn't play at all if your didn't have a decoder.

**Comment by kjgbkvhlvfiykfvil** [comment]
I mean when it won't show repeated tags like JMdict(English)

**Comment by kjgbkvhlvfiykfvil** [comment]
Windows. Ctrl+h worked, but there is no mpv folder in Roaming folder. I don't know where to find conf file

**Comment by ripose-jp** [comment]
>I mean when it won't show repeated tags like JMdict(English)

Sorry, I misunderstood what you wanted. This isn't something I've implemented and would take a little bit of know-how to do. I recommend opening a new issue as a feature request if you want this.

>Windows. Ctrl+h worked, but there is no mpv folder in Roaming folder. I don't know where to find conf file

Go to **Settings** → **Open Config Folder** and it will open the folder you need to put your `mpv.conf` in. All you need to have in it is the line `hwdec=auto`.

**Comment by xrishox** [comment]
is there a reason that these are hardcoded and not configurable? i would kind of like to be able to make the text and the window larger. it's not the biggest deal though

**Comment by ripose-jp** [comment]
It's more clutter to add to the settings if I make them configurable. There's no deeper logic to it.
