### ISSUE TITLE
Titlebar not updated when using SimpleHistory script

### ISSUE THREAD

**Issue by Issue-maker-9000** [ripose-jp/Memento#198]
When a video gets selected it should show the title of the video in the titlebar. This isn't the case when using [SimpleHistory](https://github.com/Eisa01/mpv-scripts/blob/master/scripts/SimpleHistory.lua) script and having "startup_idle_behavior" set to resume.

It is a super minor issue just a nice to see fixed if it isn't much work to do so.

**Comment by ripose-jp** [comment]
I can't reproduce this on Linux. What OS are you using?

**Comment by Issue-maker-9000** [comment]
Windows 10 21h2 ltsc channel.
No idea what the behavior is on release channel of windows 10 or windows 11

**Comment by ripose-jp** [comment]
I won't have access to Windows for about a week, so I'll have to put this on hold at least until then.

**Comment by ripose-jp** [comment]
It's reproducible on Windows. I'll have a fix up shortly.

**Comment by Issue-maker-9000** [comment]
Thanks works perfectly.
Glad it was such a small issue, have a nice day!
