### ISSUE TITLE
Unable to open media from URL's

### ISSUE THREAD

**Issue by JoshuaRamey** [ripose-jp/Memento#20]
When trying to open media from a URL (I tried with both Youtube and TVer.jp which works with MPV player) I was unable to open any media in the player. The screen is just black. Opening from local files is fine and has no problems.
It says It's unable to find MSVCR100.dll

Exact error message:
MSVCR100.dllが見つからないため、コードの実行を続行できません。プログラムを再インストールすると、この間題が解決する可能性があります。

I downloaded using the stable version on the release page, I did not build from source.

**Comment by JoshuaRamey** [comment]
[msvcr100.zip](https://github.com/ripose-jp/Memento/files/6879384/msvcr100.zip)
I was able to find the missing file online and fix the issue by adding it to the folder.

**Comment by ripose-jp** [comment]
Sounds like the people over at youtube-dl link their release against MSVC's C++ runtime.
https://ytdl-org.github.io/youtube-dl/download.html
While adding MSVCR100.dll to Memento's folder will work, the best solution is to install Microsoft's C++ runtime.
https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe

I'll be sure to add a troubleshooting section to the README for this.
