### ISSUE TITLE
Can't open on MAC M3 Arm 

### ISSUE THREAD

**Issue by childishweb** [ripose-jp/Memento#205]
“Memento 3.app” is damaged and can’t be opened. You should move it to the Bin.

Version 1.2.1 Works. Latest has issues.

**Comment by jlangeblom** [comment]
Is there also a method to take screenshots without subtitles?

**Comment by ripose-jp** [comment]
I can't reproduce this even if I run it on a system without Homebrew. What version of macOS are you running?

**Comment by jlangeblom** [comment]
Hi, 

M3 Max

Mac OS: 14.3.1

Cheers

**Comment by Toyking10** [comment]
Same issue on M1 Ultra.

Mac Studio

MacOS: 14.3.1

**Comment by Calvin-Xu** [comment]
I can confirm building from current master on M3 does not have issues.

**Comment by ripose-jp** [comment]
I can't reproduce it, so it seems like I'll have to do a fresh install to try and reproduce the issue.

**Comment by ripose-jp** [comment]
This should be fixed with v1.4.0. I've spun up a macOS 14.5 VM without Hombrew installed and was able to verify that they work there. If you continue to have issues, feel free to reopen this.

**Comment by wastu01** [comment]
I am using Mac M4 with these env, in my case it can work
- **Device**: Mac M4
- **OS**: macOS 15.5
- **Memento**: v1.6.0
- **Anki**: ⁨25.02.5
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
