### ISSUE TITLE
what settings are needed for YouTube links to work?

### ISSUE THREAD

**Issue by borisorlov21** [ripose-jp/Memento#206]
please who knows what settings are needed for YouTube links to work?
I've already figured out the sharpness settings

**Comment by ripose-jp** [comment]
The version of yt-dlp shipped with Memento v1.2.2 is probably fairly old by now so YouTube links may have broken. Try updating it according to the instructions in the [README](https://github.com/ripose-jp/Memento?tab=readme-ov-file#windows-updating-youtube-dlyt-dlp).

**Comment by borisorlov21** [comment]
thanks for the help, I'll figure it out

**Comment by borisorlov21** [comment]
I need links to YouTube to work on macOS, tell me how to do this

**Comment by ripose-jp** [comment]
There are instructions on how to do that in the part of the README I linked.
