### ISSUE TITLE
[Feature Request] Subtitle Delay

### ISSUE THREAD

**Issue by BigBoyBarney** [ripose-jp/Memento#209]
Hi!

Being able to retime subtitles on the fly (same as in mpv) would be really cool. Currently, using the mpv keybinds to change subtitle delay does not affect the memento subs.

Cheers!

**Comment by Calvin-Xu** [comment]
That is strange. I'm pretty sure it does and Memento always reads the offset from mpv.

**Comment by ripose-jp** [comment]
Memento has always respected mpv's sub-delay. I don't know what you're seeing.

**Comment by BigBoyBarney** [comment]
Interesting. I tested it now again, and it is respected. Very weird, I swear it didn't work yesterday. 
Apologies for the extraneous issue.

Cheers!
