### ISSUE TITLE
QT6 migration causes subtitle position to shift when on screen controller is shown/hidden

### ISSUE THREAD

**Issue by spacehamster** [ripose-jp/Memento#212]
Subtitle position is shifted up when the player progress bar is shown during mouse move, and shifts back down when it's hidden again. 

This issue seems to only occur after the QT6 migration https://github.com/ripose-jp/Memento/commit/afea4019a6a1c6bb5daa153490ecfa3ce9494a97

![image](https://github.com/ripose-jp/Memento/assets/3821056/6b224e46-7e42-41ea-ab18-ade58e59139b)
![image](https://github.com/ripose-jp/Memento/assets/3821056/383d16dc-a13a-49e5-b5e0-b70c0114af89)

**Comment by ripose-jp** [comment]
That is actually intended behavior if the subtitles are so low the OSC would block their visibility. However it seems to be happening in situations where the OSC would not block subtitles after the Qt 6 migration. I'll look into it.
