### ISSUE TITLE
Some elements in subtitles search are larger than expected

### ISSUE THREAD

**Issue by f8ith** [ripose-jp/Memento#223]
In the screenshot below, the part of speech is unnecessarily large.

![image](https://github.com/ripose-jp/Memento/assets/24871075/d01f43d9-2ac3-465f-bb48-392f7d5debf1)

**Comment by ripose-jp** [comment]
Probably a bug in Jitendex using some bad units to size their structured content. I don't see the issue on the latest version.

![image](https://github.com/ripose-jp/Memento/assets/72582120/c4c482f5-9841-4ba6-8aa5-d8c6c72729f6)

**Comment by f8ith** [comment]
That was the issue. Thank you for the prompt response!
