### ISSUE TITLE
Segmentation fault (core dumped) Error in Arch Linux

### ISSUE THREAD

**Issue by OllTeeP** [ripose-jp/Memento#227]
I have updated my machine and i updated to the newest version but i get this error.

> QRhiGles2: Failed to create temporary context
QRhiGles2: Failed to create context
Failed to create QRhi for QBackingStoreRhiSupport
QOpenGLWidget: Failed to create context
QOpenGLWidget: Failed to create context
Segmentation fault (core dumped)

**Comment by ripose-jp** [comment]
What are your graphics drivers, desktop environment, and are you using X11 or Wayland?

There's not a ton of information I can find on how to fix this, seems like it's a driver bug or something.

This [issue](https://github.com/ankitects/anki/issues/2738) suggests that `sudo pacman -S mesa` might solve your problem.

This [Anki forum post](https://forums.ankiweb.net/t/2-1-66-card-not-revealing/33603/4) suggests changing your renderer using environment variables.

I'd also try running Memento using XWayland if you're using Wayland to see if that fixes it.

Let me know if any of these work.

**Comment by OllTeeP** [comment]
NVIDIA, XFCE, X11.
Yeah none of these work i was going around forums too but nothing is working
I might try the flatpak version which i did one time but memento was lagging but when i tried mpv with flatpak it worked like it was supposed too, so i'll do that and see if these issues were fixed. 🙂

**Comment by ripose-jp** [comment]
If Memento worked as a flatpak but not from the AUR, I'd guess there's a bug in one of the dependencies. I can't find a ton of good information on how to fix this other than what I've already posted. You might just have do trial and error until it starts working again since I can't reproduce this. Maybe try switching to Wayland if possible?

**Comment by OllTeeP** [comment]
I restarted my system and now it works.
