### ISSUE TITLE
error while building the soruce code of Memento on Arch linux. 

### ISSUE THREAD

**Issue by djter** [ripose-jp/Memento#23]
terminal log:
mkdir -p build
cd build; cmake -DCMAKE_BUILD_TYPE=Release ..
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBZIP
    linked by target "dictionary_db" in directory /home/me/Downloads/Memento-0.5.0-1-beta/src/dict
MECAB
    linked by target "dictionary_db" in directory /home/me/Downloads/Memento-0.5.0-1-beta/src/dict

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
make: *** [Makefile:4: release] Error 1

**Comment by ripose-jp** [comment]
You're missing [libzip](https://archlinux.org/packages/extra/x86_64/libzip/) and [mecab](https://aur.archlinux.org/packages/mecab/).

I don't run Arch myself, but I know people have compiled Memento successfully on Arch and Manjaro, so it should work.

**Comment by djter** [comment]
yea my bad. i thought i had those installed.
