### ISSUE TITLE
How to hide progress bar in full screen?

### ISSUE THREAD

**Issue by ahizap** [ripose-jp/Memento#230]
Whenever the mouse moves the progress bar at the bottom shows up and it is quite distracting in full screen because we often have to move the cursor to look up words. This behavior of bottom bar can be changed by using  `script-opts=osc-deadzonesize=1` which works fine in vanilla mpv and only shows bottom progress bar when hovered over at the bottom of screen. Unfortunately in memento this does not work at all.

**Comment by ripose-jp** [comment]
Press the **Delete** key twice. If you don't have a Delete key, press **Fn** + **Backspace**. mpv's OSC options won't work with Memento because it doesn't use mpv's OSC.
