### ISSUE TITLE
video issue

### ISSUE THREAD

**Issue by wilder-duck** [ripose-jp/Memento#231]
the screen remains solid blue color while the audio plays on, but when i use anki integration to create a card , the card have the correct screenshot of the video.
![issue](https://github.com/user-attachments/assets/52208376-c202-4757-b8c2-7580f911e213)
![issue(1)](https://github.com/user-attachments/assets/86739c39-a99e-428a-9623-b690ecc88f6c)

the same file plays without any issue on mpv
![issue(2)](https://github.com/user-attachments/assets/c433c311-fe56-4f08-b410-0c5a82e794b6)

same issue with other files as well

**Comment by ripose-jp** [comment]
Update your graphics driver. That usually fixes it. If not, you're SOL for Windows. I'd recommend switching to Linux. It has the added benefit of not watermarking all your screenshots.

**Comment by wilder-duck** [comment]
Updating the graphics driver solved it. Thank you.
