### ISSUE TITLE
Is there a term marker for the translated text of the japanese sentence?

### ISSUE THREAD

**Issue by Furshia** [ripose-jp/Memento#234]
a term marker so that anki would be able to get the translated definition of the copied sentence from memento

**Comment by ripose-jp** [comment]
`{sentence-2}` and `{context-2}` already exist. You have to enable secondary subtitles to use them. You can toggle the visibility of secondary subtitles in mpv with the **Alt+v** bind.

**Comment by Furshia** [comment]
Thanks

**Comment by Furshia** [comment]
Somehow it line breaks doesnt work if the subtitle is too long on the secondary subtitles the line break just merges a subtitle therefore example instead of

But, even then, this plan is nothing more than an armchair theory.
it becomes
But, even then, this plan is nothing **morethan** an armchair theory.

**Comment by ripose-jp** [comment]
Go to **Settings** → **Options** → **Anki Integration** → Tick **Show Advanced Options**. Under **Replace Newlines With** make sure the text is `<br>`. This should be the default. If it is `<br>` and you still don't see line breaks on your cards, something in the CSS must be styling `<br>` as something other than line breaks. I can't help in that case.

**Comment by Furshia** [comment]
Thank you it worked :)
