### ISSUE TITLE
Allow scanning popup items

### ISSUE THREAD

**Issue by kik4444** [ripose-jp/Memento#239]
Lately I've been trying to use a monolingual Japanese dictionary and realized that Yomitan(chan) has one feature to make this considerably easier. You can hover over words in the popup and get a second child popup for the selected word. Then you can select another word in there and get a 3rd child popup and so on.

This is all written here in the screenshot with the `Popup` settings. https://learnjapanese.moe/monolingual/#yomichan-the-better-way-to-go-monolingual

Can this feature be added to Memento?

**Comment by ripose-jp** [comment]
Duplicate of #80.

This has been a feature for years. Just use whatever you have your modifier key set to to scan words. By default it's shift.

**Comment by kik4444** [comment]
Oh I see. Sorry for the duplicate. I keep the scan set to `Hover` so I don't hold down any modifier keys and assumed it would work just by hovering over the popup like it does in Yomitan.
