### ISSUE TITLE
Publish authoritative list of keyboard shortcuts

### ISSUE THREAD

**Issue by yangmillstheory** [ripose-jp/Memento#240]
Thanks for this excellent tool.

Is there an authoritative list of keyboard shortcuts? I see some references in code, and I know of Z and X for adjusting subtitle delays, but I'd love to see a list published in Markdown (for example).

**Comment by Calvin-Xu** [comment]
Most of the shortcuts are mpv's, like the Z and X you mentioned; you can check https://mpv.io/manual/master/#keyboard-control and https://github.com/mpv-player/mpv/blob/master/etc/input.conf

**Comment by yangmillstheory** [comment]
Thanks. Would you be opposed to an addition to the README that adds a small section with these links? That would lead to the highest discoverability IMO.

**Comment by ripose-jp** [comment]
It's prominently mentioned that Memento is an mpv frontend in the description, the top of the README, and on the .io site. I don't believe there's anywhere I could put a link to something like this in the README where people who don't know what mpv is nor have the curiosity to find out are likely to find it. I think having issues like this searchable is more than enough for the people that are having trouble with this sort of thing to get answers.
