### ISSUE TITLE
Keyboard shortcuts for seeking between and replaying subtitle

### ISSUE THREAD

**Issue by davidgz90** [ripose-jp/Memento#242]
Hello,

are there any keyboard shortcuts corresponding to the Seek to the next and seek to the last subtitle as well as one to replay the currently shown one from the beginning (same as double clicking on it the subtitle list)?

Would be nice to be able to do this without using the mouse.

Best Regards
David

**Comment by ripose-jp** [comment]
Memento is an mpv frontend. It uses the same default keybinds as mpv. You can find all of those [here](https://github.com/mpv-player/mpv/blob/master/etc/input.conf). The ones you're looking for are **Ctrl+Left** and **Ctrl+Right** for seeking to the previous and next subtitle respectively. By default no key is bound to replay the current subtitle. You can bind one to do this by adding `<Key> sub-seek 0` to your `input.conf` in Memento's configuration directory. This directory can be found by going to **Settings** → **Open Config Folder**.

**Comment by davidgz90** [comment]
Much appreciated, worked like a charm.
