### ISSUE TITLE
Just clicking "Apply" in the Interface settings alternates the UI theme between System and the selected theme

### ISSUE THREAD

**Issue by precondition** [ripose-jp/Memento#244]
Version: 1.4.1 (manually compiled with my aggregate-frequency-marker commit as the latest checked out commit)
OS: Ubuntu with XFCE DE (i.e. X11 server, not Wayland)

Changing any of the color properties of subtitles (text color, background color, stroke color) correctly applies the change to the subtitle but also resets the whole UI theme to Light.

A demo with changes to the background color is available below:

https://github.com/user-attachments/assets/d1bfca96-add5-49f8-923a-0892bb6cc416

This has to be a regression because I remember being able to switch between a thick black subtitle background and a transparent background without changes to the overall theme. If I recall correctly, the working version I was using before was still running Qt5. If I have the time, I may try to track the commit that introduced the regression.

**Comment by ripose-jp** [comment]
I can't seem to reproduce this on Plasma 6 X11. Is it possible you could step through [`MainWindow::initTheme()`](InitinitThemeinitThemeinitTheme) after clicking apply to see if anything interesting happens? Normally I'd expect the switch to handle the `Constants::Theme::Dark` case.

**Comment by precondition** [comment]
I connected a debugger via CLion with a breakpoint on `MainWindow::initTheme` but the runtime value of `theme` in:

```cpp
    Constants::Theme theme = static_cast<Constants::Theme>(settings.value(
            Constants::Settings::Interface::THEME,
            static_cast<int>(Constants::Settings::Interface::THEME_DEFAULT)
        ).toInt());
```

is always shown to `Constants::Theme::Dark`.

I also tried disabling the custom style sheets in case that had an effect but in vain.

I also noticed that changing the subtitle color properties does not simply reset the interface theme to Light every time. It actually alternates between Light and Dark.

**Comment by precondition** [comment]
I can also confirm that versions running Qt5 built with a version before the commit below:

```
commit afea4019a6a1c6bb5daa153490ecfa3ce9494a97 (HEAD)
Author: Ripose <ripose@protonmail.com>
Date:   Sun Mar 10 15:23:57 2024 -0700

    cmakelists: migrate to qt6
    
    Migrates Memento to Qt6. This is important since Plasma 6 is out of beta
    in February. There will likely not be a new release until then. Reworks
    SubtitleListWidget to use std::shared_ptr since what was safe in Qt5
    using QList is no longer safe in Qt6 due to the merging of the QList and
    QVector implementations.
    ```
    do not exhibit the bug and checking out that commit or anything after starts exhibiting the bug.

**Comment by precondition** [comment]
I can confirm that the bug appeared with the introduction of the commit below:

```
commit afea4019a6a1c6bb5daa153490ecfa3ce9494a97
Author: Ripose <ripose@protonmail.com>
Date:   Sun Mar 10 15:23:57 2024 -0700

    cmakelists: migrate to qt6
    
    Migrates Memento to Qt6. This is important since Plasma 6 is out of beta
    in February. There will likely not be a new release until then. Reworks
    SubtitleListWidget to use std::shared_ptr since what was safe in Qt5
    using QList is no longer safe in Qt6 due to the merging of the QList and
    QVector implementations.
```

Something probably changed in the way Qt6 handles themes and palettes compared to Qt5.

**Comment by precondition** [comment]
I experimented with the initialization of the `pal` variable at the start of `MainWindow::initTheme()` and I discovered that the default initialization (`QPalette pal{}`) does not affect the bug while initializing the variable with the standard palette (`QPalette pal{QApplication::style()->standardPalette()}`) seemingly gets rid of the bug.

**Comment by ripose-jp** [comment]
If you want to make a PR with the `QPalette pal{QApplication::style()->standardPalette()}` solution, I'd be fine with that. Or I can do it, which every works for you.
