### ISSUE TITLE
Audio not playing (button greys out on clicking)

### ISSUE THREAD

**Issue by WhoMI7** [ripose-jp/Memento#246]
![image](https://github.com/user-attachments/assets/9a5618e2-b12a-4285-853d-225606ef6876)
Can't play audio here
Tried setting up https://github.com/yomidevs/local-audio-yomichan which works for yomichan but not for memento

**Comment by ripose-jp** [comment]
Duplicate #137 

local-audio-yomichan has been incompatible with Memento for years because they don't send the `content-length` header.
You can modify the code according to this [post](https://github.com/ripose-jp/Memento/issues/137#issuecomment-2058104149) and it should fix it.
