### ISSUE TITLE
Create chocolatey installer package

### ISSUE THREAD

**Issue by jakublevy** [ripose-jp/Memento#25]
Hey,
what a useful video player you have here! Exactly what I was looking for 👏🏻.
I maintain some packages for Chocolatey, so I created one for memento.

https://community.chocolatey.org/packages/memento.portable
(The package has to undergo a moderation process now.)

If you could provide an installer binary, I could also create and maintain packages memento (metapackage) and memento.install.

**Comment by ripose-jp** [comment]
I don't mind making an installer, but I can't do it for v0.5.0. Making an installer would requiring changing the directory structure of Memento on Windows, which means I would need to change the source code. It'll have to be put off to a future version.

**Comment by jakublevy** [comment]
That would be great.

Consider this issue more like a notification that there already exists a Chocolatey package.
I have a choco au script for auto-update, so I will keep an eye on new releases and if it would contain an installer I would create the remaining choco pkgs.

I will rename this issue to "Create chocolatey installer package" to make sense and keep this issue open.

**Comment by ripose-jp** [comment]
An installer was added for the release of [v0.5.1](https://github.com/ripose-jp/Memento/releases/tag/v0.5.1-beta)

**Comment by jakublevy** [comment]
Great, thanks.
The installer package was created and updates to 0.5.1 were pushed to Chocolatey.
