### ISSUE TITLE
How do I uninstall Memento on Linux?

### ISSUE THREAD

**Issue by Feripe-a** [ripose-jp/Memento#27]
I found about Memento today and tried it out. But I can't uninstall it. I installed it via Github following your instructions.

**Comment by ripose-jp** [comment]
Type `sudo make uninstall` in the directory where you cloned the repository.
You'll have to manually remove any configuration files in `~/.config/memento`

**Comment by Feripe-a** [comment]
Lol. It was obvious. This is my first time doing such a thing. I'm new at Linux.
