### ISSUE TITLE
Unexpected mpv config directory on MacOS

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#28]
On MacOS, the `input.conf` at `~/.config/mpv/input.conf` apparently is not read. This can be solved by copying it to Memento's own config directory at `~/Library/Preferences/memento`. I have not yet tested the case with `mpv.conf`.

The behavior is certainly unexpected, though perhaps it can be beneficial in allowing bespoke mpv configurations for Memento. In any case, we probably should note it somewhere?

Thanks for this really cool work!

Discovered while checking the following issue:

> Nice catch with the double seek, I'll fix it in the next release.
> 
> As for changing the default keybinds, I'd rather not so Memento remains functionally as close to mpv as possible.
> 
> You can implement the behavior you want pretty easily by adding these lines to your input.conf.
> 
> ```
> ENTER   sub-seek        0
> RIGHT   sub-seek        1
> LEFT    sub-seek        -1
> ```
> 
> Check the README to find the location of the config directory for your operating system.
> 
> These links will be helpful for finding out what the default binds are and how to configure you own custom binds:
> https://mpv.io/manual/stable/
> https://github.com/mpv-player/mpv/blob/master/etc/input.conf

_Originally posted by @ripose-jp in https://github.com/ripose-jp/Memento/issues/3#issuecomment-815157142_

**Comment by ripose-jp** [comment]
I intended for the configuration section in the README to mention that, but after re-reading it, I agree that I could have said it better.

I've updated the README to say more clearly Memento and mpv's configuration directories are separate.
