### ISSUE TITLE
Double subtitles now displaying 

### ISSUE THREAD

**Issue by nikgtasa** [ripose-jp/Memento#32]
![image](https://user-images.githubusercontent.com/38408810/134427828-5079a854-ee69-4f71-9703-4917663f0380.png)
When selecting second row of subtitles they don't display. Tried different files but issue persists.
Win10 21H1, latest memento.

**Comment by ripose-jp** [comment]
Duplicate #12

>I'm not certain this is a bug exactly, but more of a trade off of having subtitles appear over the player.
>
>If you want to use the second subtitle track, I recommend going to Settings -> Options -> Search and unchecking "Hide mpv subtitles when search bar is visible" and checking "Hide search bar when playing media".
>
_Originally posted by @ripose-jp in https://github.com/ripose-jp/Memento/issues/12#issuecomment-839904616_

Additionally, I also recommend setting the searchable subtitles to have a background color if you have trouble reading them overlayed on top of mpv's subtitles.
