### ISSUE TITLE
Typo in uninstaller

### ISSUE THREAD

**Issue by ElaxDev** [ripose-jp/Memento#36]
When you are going to uninstall Memento in windows and it asks for confirmation the message says "permanantly uninstall Memento?" and it should be "Permanently uninstall Memento?".

Although I think another question would be better, like "Are you sure you want to permanently remove Memento?" or something like that.

Screenshot:
![image](https://user-images.githubusercontent.com/31047609/135317956-e9bb2296-ffd7-4b94-b735-2620162bfa8a.png)

**Comment by ripose-jp** [comment]
Thanks for reporting this. The install script was basically copied from the [NSIS wiki](https://nsis.sourceforge.io/A_simple_installer_with_start_menu_shortcut_and_uninstaller), which also unfortunately has the typo.
