### ISSUE TITLE
Add the ability to have the audio of multiple subtitle lines.

### ISSUE THREAD

**Issue by ElaxDev** [ripose-jp/Memento#38]
Sometimes just the current subtitle line is not enough to give context to the word you want to mine, so it would be good to have a way of selecting multiple adjacent subtitle lines, maybe in the subtitle browser and then when you click the button to mine it records the audio of the selected subtitle lines and add them to the sentence field.

**Comment by ripose-jp** [comment]
Just to clarify, you would like a version of `{audio-media}` that captures all the audio of `{context}`?

**Comment by ElaxDev** [comment]
Exactly, actually I didn't know `{context}` existed since I used `{sentence}`, so yeah that's the thing that would be lacking.

**Comment by ripose-jp** [comment]
Added on master.
It will make it into the next release probably around the end of December.
