### ISSUE TITLE
make it so that you can change the position, size and font of the scannable sub-line

### ISSUE THREAD

**Issue by fatslob12** [ripose-jp/Memento#4]
make it so that the sub line you can scan can be modified like the standard subtitle line can in mpv ie change size, position and font. would also be cool if those settings could be saved as default so you dont have to change it each time you open the program

**Comment by ripose-jp** [comment]
Assuming you're on v0.4.4, you can change the look and feel of it.

Go to Settings -> Options -> Interface, check enable custom style sheets, and then edit the one corresponding to the subtitle search bar.

It takes minor CSS experience, but it should be pretty easy to pick up by just modifying what's already there.

**Comment by ripose-jp** [comment]
Not sure why this was closed, but v0.4.5 resolves it.
