### ISSUE TITLE
Add Yomichan-sytle search for creating cards

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#47]
I hate to be the one asking for feature creep, but here is something to consider. Currently, when looking up a word such as`追いはぎ`, `持ちこたえる`, `叩きだす`, etc, where the first part is in the conjunctive form and the second part is in kana, Memento is not able to look up the whole word but separates it into two (at least with my set of dictionaries). After editing the subtitle to rewrite the second part of the word in kanji also (追い剥ぎ、持ち堪える、叩き出す), Memento is able to look up the whole word.

I think this is a difficult problem and Yomichan does not handle this case well either. But there have been other cases where the word form is too weird for Memento to recognize (one I can think of is 混とん vs 混沌). I wonder if any of the following are possible:

* ~~allow the user to select part of the subtitle to look up as the headword as a whole~~ (I doubt this is what causes the issue in the example; I ran these words through Mecab and each is recognized as an individual token)

* have an interface that the user could open & manually input a word (in the dictionary form that Memento should be able to recognize) to look up with Memento’s dictionary, and be able to add the result to Anki with the relevant screenshot and context. This seems like a catch-all solution for these scenarios that don’t happen very often.

**Comment by ripose-jp** [comment]
Solving this problem without just putting any and every possible form of a word in the database is a job for someone who is has an extensive background in Japanese linguistics. I'm not going to be of any help there.

Is the solution you're proposing basically to just allow a user to search for any word they like and then make a card from that as if it were contained in the subtitle?

**Comment by Calvin-Xu** [comment]
> Is the solution you're proposing basically to just allow a user to search for any word they like and then make a card from that as if it were contained in the subtitle?

Yes exactly

**Comment by ripose-jp** [comment]
The feature has been implemented on master. It can be accessed by going to Settings > Show Subtitles or using Ctrl+R.

No idea if it is bug-free, but it seems fine. This feature has the capability to introduce a lot of subtle problems just from how much had to be changed to get it to work (4fa8ac8fd0b794998e26bd9211f961e21b7e89f9), so I'll leave this open for a bit.

**Comment by ripose-jp** [comment]
I don't believe this feature has any more serious bugs.
