### ISSUE TITLE
Where can I find the settings?

### ISSUE THREAD

**Issue by geoals** [ripose-jp/Memento#5]
> No dictionaries are installed. For subtitle searching to work, please install a dictionary.
> Dictionaries can be found here.
> To install a dictionary, go to Settings -> Options -> Dictionaries.

But where can I find settings? I assume it is the hamburger menu in the bottom-right corner, but nothing happens when I click it.
I'm on Linux, Manjaro with KDE.

More info: I installed the latest release 0.4.4 with 
```
make
sudo make install
```

**Comment by ripose-jp** [comment]
At the top in the menu bar.

The hamburger icon open and closes the subtitle list.
