### ISSUE TITLE
Option to separately (de)select {audio-context}

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#51]
Currently, selected lines of subtitles can have their text and audio exported to Anki with `{context}` and `{audio-context}` respectively. But there are cases where having less audio than text is preferable.

Consider a line at the end of an exchange, whose context is provided by the lines preceding it. If a lot of lines preceding it have to be selected, then `{audio-context}` exports a long segment of unrelated audio before getting to the vocab itself, which slows down the pacing of reviews. A more ideal option might be to keep the all the text while only exporting the audio of the relevant line (or fewer lines).

I think it could be nice if there is an option to enable a checkbox for each (selected) line in the subtitle list. When the user selects the line, they are checked by default, but the user has the option to uncheck lines to remove them from `audio-context`.

**Comment by ripose-jp** [comment]
Why wouldn't you just use `{audio-media}` instead if the selected context is too long?

I don't really want to make adding cards any harder than it already is. Adding more UI elements to the Subtitle List seems like it'd only make it more confusing, especially for something niche like wanting audio from more than one subtitle but text from a different set of subtitles.

**Comment by Calvin-Xu** [comment]
I see. {audio-context} is awesome in 99% of the cases, but sometimes finer control is great.

As an alternative, would you consider a feature where the user can copy the text of (multiple) selected lines in the subtitle list? If it's mapped to a keybind like Ctrl-C there would be no additional UI elements. Currently double clicking on the subtitle copies that line.

**Comment by ripose-jp** [comment]
I've implemented Ctrl+C as a shortcut to copy the currently selected context. It's up on master.
