### ISSUE TITLE
Option to normalize {audio-media} or {audio-context} volume against {audio}

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#52]
Might be a nice feature to have, but I can understand if it is difficult to implement without introducing more dependencies or cause performance issues.

**Comment by ripose-jp** [comment]
Normalizing `{audio-media}` and `{audio-context}` is easy. Normalizing it to `{audio}` is not because those are remote files and they may not even exist.

I'd be willing to add an option to normalize to a user specified dB value, but not so much to `{audio}` specifically.

**Comment by Calvin-Xu** [comment]
That seems great too. JapanesePod101's audio loudness seems to vary from -14 to -25 (integrated) LUFS across my samples. -19.776 is the mean value I found if they may be a data point for determining the default.

**Comment by ripose-jp** [comment]
Thanks for getting the average volume of JapanesePod's audio clips. I've added an option to normalize audio and the default value is -20 dB. Everything sounds about as loud as JapanesePod, so it seems like a good default.

The changes are up on master.
