### ISSUE TITLE
Can't take screenshot

### ISSUE THREAD

**Issue by OltiP2** [ripose-jp/Memento#58]
![RH  K-On! - 07  Dual Audio   BDRip   1080p  - Memento 1_9_2022 8_53_35 PM](https://user-images.githubusercontent.com/97410429/148700742-48daf23d-7b40-4baf-83e4-6048dc875dc3.png)
Im not sure if this was already an issue but i cannot take any screenshot with or without subtitles

**Comment by Calvin-Xu** [comment]
mpv might not have permission to the directory it is trying to write to. Try setting screenshot-directory=an accessible dir in your mpv.conf

**Comment by OltiP2** [comment]
> mpv might not have permission to the directory it is trying to write to. Try setting screenshot-directory=an accessible dir in your mpv.conf

Where do i find that mpv.conf i've searched for it but i cannot find it

**Comment by ripose-jp** [comment]
1. Settings > Open Config Folder
2. Create a file called `mpv.conf`
3. Add this line `screenshot-directory=~~desktop/`
4. Restart Memento

**Comment by OltiP2** [comment]
Thank you it's working now
