### ISSUE TITLE
Cosmetic: ankisettings UI alignment

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#60]
Seeing that work is being done to declutter the UI there, I want to bring up that a bunch of UI elements in ankisettings are out of alignment (they are supposed to be all left-justified but miss by pixels from each other), and vertical spacing is also a bit inconsistent, at least on macOS. I tried to add some more constraints but turns out I don't know how to use the design tool at all.

**Comment by ripose-jp** [comment]
I've done my best to make it nicer, but at the end of the day much of the problems are due to that limitations of the macOS Qt style. You can test that it doesn't happen on other styles by changing the theme to Dark or Light.

My best effort fix is up on master.

**Comment by Calvin-Xu** [comment]
Ah I see. But it is much nicer now!
