### ISSUE TITLE
Use of YouTube automatically generated subs

### ISSUE THREAD

**Issue by ksesong** [ripose-jp/Memento#61]
YouTube's auto-generated subs are not available. While they cannot be trusted, they are often useful to segment the track, and a good base for Anki cards. Such subtitles can already be downloaded with `yt-dlp`, e.g `yt-dlp --write-auto-subs --sub-langs 'ja'`.

Ideally, there would be a way to edit a subtitle line to change mistranscribed characters ahead of a card creation.

**Comment by ripose-jp** [comment]
You could try some of the stuff mentioned in this https://github.com/mpv-player/mpv/issues/8518 in your `mpv.conf`
