### ISSUE TITLE
Better display of ordered lists that use Japanese circular numerals

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#62]
Currently, the TermWidget converts new lines in the glossaries to an unordered list. Overall I think this improves readability, but it looks bad when dictionaries use Japanese circular numerals for numbered lists:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/28978265/149246694-c8d50340-25bd-4e37-a1e9-d8fee4887bfe.png">

Characters ① through ⑳ occupy a continuous code range and can be matched with `"[\\x{2460}-\\x{2473}]"`. I toyed with converting these lists to a nested ordered list (removing the characters and any whitespace after), but can't find a good solution. Would like to know if you think some improvements can be done.

Comparisons: do not convert to ordered list:
<img width="383" alt="image" src="https://user-images.githubusercontent.com/28978265/149247835-7b841104-2998-4f3c-99d0-8d3032687a44.png">
Comparison: strip line breaks
<img width="418" alt="image" src="https://user-images.githubusercontent.com/28978265/149247619-f0015bbd-04bf-4341-97e8-1831e5976b2c.png">

**Comment by ripose-jp** [comment]
I made it the way it is because it's easier to tell apart new lines from word wrap. I don't really like any of the alternatives you've proposed and would rather keep as it is now.

**Comment by Calvin-Xu** [comment]
Hmm I see. I thought making the numbered lists `ol` would be a good middle ground between readability and appearance, but it is probably much ado about nothing.

On the other hand, I am beginning to like displaying the glossary as is with the line breaks intact. It uses more horizontal space that is at a premium in the TermWidget, and also is Yomichan's default look.

I've added a PR that adds an option to toggle off list conversion behavior. Perhaps this can be considered?
