### ISSUE TITLE
Copy {audio-context}

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#63]
Currently `Ctrl C` copies the text of the currently selected context. It might be nice if the {audio-context} can be copied with a shortcut like `Shift Ctrl C`. I tried to implement this feature, but realized that ideally audio padding & volume normalization values should be the same as in Anki Integration settings, and not sure if it should have access to the config object or if there is a better way.

**Comment by ripose-jp** [comment]
I willing to implement this feature, but I believe it should operate independently of Anki Integration settings. The primary reason for this is I'd like Memento to be fully featured even with Anki Integration disabled. It would be a bad thing if features unrelated to Anki would need Anki Integration enabled to work to their fullest extent. That would mean this feature would be implemented without the option to normalize or pad audio.

**Comment by Calvin-Xu** [comment]
I think that makes sense. One thing I was thinking of was that in case Memento allows audio formats other than AAC in the future in Anki settings (currently the image format can be set). Possibly this feature will always fall back to AAC then.

**Comment by ripose-jp** [comment]
What's the benefit of supporting other audio formats? AAC is free, widely supported, has decent file sizes, and no one is realistically going to hear the difference.

The only reason multiple image formats are supported is because PNG was originally the only used format, but that ending up using a massive amount of space. I respect that dae makes syncing Anki free and doesn't accept donations. I wouldn't want to contribute wasting storage space and effectively his money. I only add the option because there are a lot of cases where people can tell JPGs apart from PNGs and it really does bother them. WebP would be the default if it were more widely supported.

Other than that, the feature is up on master.

**Comment by Calvin-Xu** [comment]
In no way advocating for other audio formats to be supported. I guess it occurred to me how OGG Vorbis not supported on iOS and some people just want MP3. But yeah silly as AAC is supported everywhere now.

**Comment by Calvin-Xu** [comment]
So it seems that at least on macOS, Anki refuses to import a `.aac` audio file from the clipboard. Pasting it into an Anki field results in something like `file:///private/var/folders/31/xkn6lwrs7_382lqhy5f9wzbc0000gn/T/memento.pithWi.aac`.

It seems that just changing the extension to `.m4a` works, although I guess that might not be very ideal. Can this be addressed with ffmpeg or some other way?

**Comment by ripose-jp** [comment]
I don't know how Anki likes to do things, but the same thing that happens when I try to directly paste the file on Linux. I can click the paperclip, paste the file into my file picker and that works just fine. If you directly can paste m4a, but not aac files into Anki, that sounds like their bug.

**Comment by Calvin-Xu** [comment]
I see. macOS does not allow pasting into the file picker. When I opened the directory, it seems that Anki refuses to open it either way:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/28978265/149458252-1a25d8d9-5ef5-4e2b-80a3-5324cd4674d9.png">

Other .aac files I've tried (from https://filesamples.com/formats/aac) don't work either:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/28978265/149458550-e49c429c-c650-4c75-ae69-7f09d5887bd2.png">

It seems that `.aac` is not listed as an audio extension here: https://github.com/ankitects/anki/blob/db804d95442c86bdba206c15128344cea41493ff/qt/aqt/sound.py#L83

**Comment by ripose-jp** [comment]
Do you want to make PR adding aac support to Anki? You found the issue, so I don't want to take the opportunity from you.

**Comment by Calvin-Xu** [comment]
lol I would not have thought of it if you haven’t said so. I think I’ll have a try even though I feel it is challenging.

After some more looking around it seems that the editor is supposed to accept .aac, along with quite a number more formats: https://github.com/ankitects/anki/blob/404a1a1f6d7a22051e6d677d21f386b947411149/qt/aqt/editor.py#L61

**Comment by Calvin-Xu** [comment]
So turns out this exact problem was fixed a month ago: https://github.com/ankitects/anki/commit/8306bc1e25b94704221d2a115c0c02464db29b29. It is currently in ⁨2.1.50 (dev)⁩. I guess there is nothing to do right now.
