### ISSUE TITLE
Ctrl-C when the subtitle list is not open quits Memento

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#67]
Ctrl-C is implemented as a shortcut in SubtitleListWidget that copies the current `context` to clipboard. When the subtitle list is not currently open, the shortcut quits Memento. I guess the implementation implies this, but it is not very intuitive. I suppose the expected behavior is that the current line will be copied, like how context behaves when adding to Anki even when the subtitle list is not visible. On the other hand, Shift-Ctrl-C does not do anything when the subtitle list is not open and does not quit Memento.

**Comment by ripose-jp** [comment]
Not changing default mpv binds is one of the design philosophies of Memento.

Add `Ctrl+c ignore` to your `input.conf` to change the behavior.

**Comment by Calvin-Xu** [comment]
I see. I always thought q is the keybind to quit. Qt remaps Command to Ctrl on Mac and passes to mpv so it was confusing.

**Comment by ripose-jp** [comment]
The whole quitting with `ctrl+c` thing is probably a homage to killing things with `ctrl+c` on Unix. The only difference between it an `q` is that `ctrl+c` quits mpv with an exit code of 4, though Memento will still quit with 0.

**Comment by Calvin-Xu** [comment]
Yeah. It's just that on Mac, Ctrl-C in Memento does not quit because I think Ctrl gets mapped to Meta by Qt, but Cmd-C does. In mpv the opposite is true (Ctrl is Ctrl, Cmd is Meta). Not sure if you'd consider this changing default mpv keybindings; it's pretty consistent so I don't feel it's a problem.
