### ISSUE TITLE
Support displaying ruby text in glossary

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#73]
Some dictionaries seem to use parentheses, bug some use ruby tags that would be cool if supported.
Yomichan:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/28978265/151070338-5e3f94f4-6b7c-44f3-9cb1-8483469733a0.png">
Ruby:
<img width="311" alt="image" src="https://user-images.githubusercontent.com/28978265/151070384-7560df9d-fa98-4797-a2e5-d4872fd5eeaa.png">
Related Yomichan issue:
https://github.com/FooSoft/yomichan/issues/1655

**Comment by ripose-jp** [comment]
Qt's rich text engine doesn't support `<ruby>` tags, so it's not possible without importing QtWebEngine. But at that point, I might as well just chuck out everything and bundle in Yomichan since that becomes possible.

The solution is worse than the problem in this case, so I can't fix this.
