### ISSUE TITLE
No pitch accent support

### ISSUE THREAD

**Issue by nonetrix** [ripose-jp/Memento#74]
It seems it doesn't have support for {pitch-accents}
![image](https://user-images.githubusercontent.com/45698918/151649325-257ecd44-76ef-47a2-a6f9-7b8cfd9e177a.png)

**Comment by ripose-jp** [comment]
Memento is not Yomichan so not all the markers are the same. The marker you're looking for is called `{pitch}`.

Press the **Help** button in Anki Integration settings for a complete list of markers.

**Comment by nonetrix** [comment]
Is there any documentation?

**Comment by ripose-jp** [comment]
Most of the documentation are in tool tips and the help buttons under the various settings. The few things that don't fit neatly into that way of doing things are in the Troubleshooting section of the README and the change logs on the Releases page.

Feel free to ask question in the issues if you can't find something. If it's a question, I'll just tag as such.
