### ISSUE TITLE
Issue: No tutorial

### ISSUE THREAD

**Issue by quietmansoath** [ripose-jp/Memento#76]
There's no tutorial. I have Anki connect, dictionaries installed, everything, but there's no instructions on how to use this. I have no idea what to type in the values of the term section of the field, no way to add anki cards, and it seems it's not possible to grab the audio from the show?

**Comment by ripose-jp** [comment]
I put help buttons and tool tips all throughout the settings exactly for this purpose.

![image](https://user-images.githubusercontent.com/72582120/151714677-534869b7-afad-4886-b9be-2850188f5596.png)

I don't know what a possible Memento tutorial would consist of considering that everyone has different workflows and needs.

**Comment by Calvin-Xu** [comment]
The ergonomics of Memento is modeled closely after Yomichan, which really does not have a tutorial either but much more extensive explanations for options. You might want to check out the various tutorials online about Yomichan's Anki integration to get an idea.

**Comment by ripose-jp** [comment]
I left this open in case you wanted to leave some feedback that could help me handle this better, but since it's been a few days with nothing I'm going to close this.

**Comment by quietmansoath** [comment]
Sorry, I missed these notifications.

Okay so 1. I was dumb and totally missed that help button. That tells me that it should probably be more prominent, like even by being a different color so it doesn't blend it with everything else.

Next, a better integration might be to offer the term and kanji markers as a dropdown, in addition.

Finally, @Calvin-Xu , the term markers in this app and in Yomichan aren't the same so, without having that key that the help button provides, knowing how Yomichan works isn't really useful.

Anyway, thanks @ripose-jp for responding. I hope the feedback is useful. I'll be coming back here to give this a second try.

**Comment by ripose-jp** [comment]
> Okay so 1. I was dumb and totally missed that help button. That tells me that it should probably be more prominent, like even by being a different color so it doesn't blend it with everything else.

I can't do this. Even if a big read button that says **HELP** is an eye catcher, it's really ugly and almost certainly breaks any conventions of good style.

> Next, a better integration might be to offer the term and kanji markers as a dropdown, in addition.

This is something I can actually do.
![image](https://user-images.githubusercontent.com/72582120/152663731-4f8be8da-fa2c-497f-858b-1d1b2a27d8dc.png)

**Comment by quietmansoath** [comment]
> Even if a big read button that says **HELP** is an eye catcher, it's really ugly and almost certainly breaks any conventions of good style.

Fair enough.

> This is something I can actually do.

Yeah, that would be great!
