### ISSUE TITLE
Open file dialouge doesn't always work when video is played

### ISSUE THREAD

**Issue by eyalmazuz** [ripose-jp/Memento#77]
Most of the time (mainly in full screen mode), if a video is currently played, pressing the open file button opens the dialogue but it doesn't present it although it get focused on, which mean you can navigate and pick other videos to play but you don't see the menu.
some times it also happens in windowed mode but not all the time.

while this happens you can paused the video and need to press esc 1-2 times to close the open file dialogue in order to regain control.

memento version: 0.5.4-1-beta
os: Ubuntu 20.04.3

example video: https://streamable.com/vtwufp

**Comment by ripose-jp** [comment]
Should be fixed on master.
