### ISSUE TITLE
Hide subtitles unless paused

### ISSUE THREAD

**Issue by ksesong** [ripose-jp/Memento#82]
I propose a toggle that hides subtitles unless the playback is paused, giving viewers a chance to listen and parse the audio, with the objective of reducing our dependence on subtitle reading. 

This would also work well with the existing "Auto Pause" function.

**Comment by Calvin-Xu** [comment]
There already is a "Hide subtitle search when playing media" that hides Memento's subtitles, and it works with auto pause.

If you want this behavior from mpv, some scripting should work.

**Comment by ksesong** [comment]
When setting the "Hide subtitle search when playing media" option, it does hide Memento subtitles as I proposed, but mpv subtitles are shown instead (they have a different styling). I am not very familiar neither with mpv nor with how Memento subtitles are handled, but I have tried to use the shortcut `V` to hide mpv subtitles, which works until they re-appear as soon as the playback is un-paused.

**Comment by Calvin-Xu** [comment]
This is curious. The v shortcut (lowercase) toggles subtitle visibility by default and should not be affected by play/pause. You can check this on a vanilla mpv build and check your input configs.

**Comment by ripose-jp** [comment]
You can already do this.
1. Go to **Settings → Options → Search**
1. Uncheck "Hide mpv subtitles when subtitle search is visible"
1. Check "Hide subtitle search when playing media"
1. Turn off mpv's subtitle visibility by pressing `v` or adding `sub-visibility=no` to your `mpv.conf`.
