### ISSUE TITLE
Custom seperation for multiple-line sentence contexts in exported Anki cards

### ISSUE THREAD

**Issue by dkaknbk** [ripose-jp/Memento#85]
Would it be possible to have an option to choose between different characters to separate the individual lines of longer contexts in the exported Anki cards? The current implementation seems to be a new line for each line of the subtitle, but that ends up looking rather messy for sentences with longer context that are split up between many lines (see below). Ideally, I'd like there to be a user defined option similar to the already existing "Replace new lines in subtitles with", except it applies for the exported Anki cards. For example, I personally like to use the Japanese-style wider space "　" as a separation between lines when I post-edit the cards, makes them easier to parse for me than either nothing or new lines.

Here is an example of a card that is a bit of a hassle to post-edit, for which such implementation would be useful:
![anki_2022-02-20@06_27_31](https://user-images.githubusercontent.com/78300742/154829800-9463af87-c1c4-44f9-90cb-d6d4c38f8173.jpg)

Also, as a side note, even contexts that only consist of a single line always end up with a useless empty new line at the very end of the sentence, as well. It would be nice if that behavior could be adjusted, as well.

Thanks for the consideration, big fan of your work!

**Comment by ripose-jp** [comment]
This should be a pretty trivial feature to add. I'll get to it when I finish #72.

**Comment by ripose-jp** [comment]
This was just added on master.

>Also, as a side note, even contexts that only consist of a single line always end up with a useless empty new line at the very end of the sentence, as well. It would be nice if that behavior could be adjusted, as well.

This isn't something Memento does, it just happens that some subtitles end with a blank newline. I think this is a poor man's way of adding some space between the bottom of the screen and the subtitles. You can remove it by using a regex filter in **Settings** → **Options** → **Search**. `^(?:[\t ]*(?:\r?\n|\r))+` may work, but I haven't tested it.
