### ISSUE TITLE
Adding to Anki

### ISSUE THREAD

**Issue by Mortiganto** [ripose-jp/Memento#86]
When hovering over a word I never get the option to add, only view in anki. Is this a bug or am I missing something?
![subError](https://user-images.githubusercontent.com/100338117/155470407-6a9875c0-39c6-4a98-b45b-2183d514248b.jpg)

**Comment by ripose-jp** [comment]
That happens when you mess up your card template.
Post a screenshot of it.

**Comment by Mortiganto** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/100338117/155481678-5b6514ed-f5bc-4435-a294-f8bbc11342fe.png)

**Comment by Calvin-Xu** [comment]
Try putting {expression} into Word.

**Comment by Mortiganto** [comment]
That fixed it! Thank you!
