### ISSUE TITLE
Ability to collapse a search result (term definition)

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#90]
When the top result is not desirable and many dictionaries are loaded, it can be time-consuming to scroll through to get to the right result. The ability to collapse/expand a term definition would greatly improve the experience.

**Comment by Calvin-Xu** [comment]
Thank you! One edge case I've found is that when the last definition currently displayed (within the user's search limit) is collapsed, the collapsed definitions all shift and become bigger uniformly to fill up the space, until "Show more results" is clicked.

I think it would be more ergonomic if collapsing the last displayed entry triggers showing more results. The jank might still be there when reaching the last search result, if that is worth being addressed.

**Comment by ripose-jp** [comment]
I fixed what I believe you described. 

>I think it would be more ergonomic if collapsing the last displayed entry triggers showing more results.

Not going to happen. Buttons should only do what the user expects them to do. Something like infinite scroll would make more sense since it's in line with user expectations.

**Comment by Calvin-Xu** [comment]
Thank you, that behavior has been fixed. There seems to be some additional graphical jank, possibly having always been here, when clicking on “Show more”. It seems as if the additional definitions are displayed on top for a moment before getting pushed down. Wondering if that might also worth looking into.

**Comment by ripose-jp** [comment]
I don't think it would be easy to fix. You'll just have to put up with the flicking during large UI updates because that's how Qt likes to do things.
