### ISSUE TITLE
Could not extract dictionary resource

### ISSUE THREAD

**Issue by Rik-Kirtaniya** [ripose-jp/Memento#93]
Hi, I just downloaded the latest 0.5.5 windows installer of Memento and after installing it, I am trying to add the zip files of the dictionaries to it, but it keeps showing up the error: "Error adding dictionary: Could not extract dictionary resources.".

The debug console shows the following:
_QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
Could not remove base path: C:/Users/Manager/AppData/Local/memento/res//JMdict (English)
Error Code: 7c_

I am using Windows 10 Pro, Version 21H1, OS Build 19043.1566

I would really appreciate if you could help me out with this.

**Comment by ripose-jp** [comment]
You found a critical bug. I'll get a fix release out ASAP.

You can get around it by going to **Settings** > **Open Config Folder** and creating a folder called `res`.

**Comment by Rik-Kirtaniya** [comment]
Thank you for the prompt reply, the importing works perfectly now.

By the way, there was one more error message in red letters in the debug console previously, which was something pertaining to not finding a file called "input.conf", and the error disappeared when I created a file by that name. Just letting you know in case that helps.

**Comment by ripose-jp** [comment]
That's just mpv telling you you don't have an `input.conf`. If you're not interested in rebinding keys you can just ignore it.

**Comment by ripose-jp** [comment]
I just released [v0.5.5-1](https://github.com/ripose-jp/Memento/releases/tag/v0.5.5-1-beta) which should fix all these issues. It's strongly recommended to update.
