### ISSUE TITLE
OSC visibility toggle?

### ISSUE THREAD

**Issue by Rik-Kirtaniya** [ripose-jp/Memento#95]
Sorry if this is a dumb question but I am trying to change the visibility of the OSC by using the "del" key which is said to "Cycles visibility between never / auto (mouse-move) / always" in the mpv manual, but it does not seem to work here. I tried putting a custom option line in the input.conf file as: 
_"a script-message osc-visibility never
b script-message osc-visibility auto"_
as suggested in the mpv manual as well, but that did not seem to work either. Is there a way to do this, that is, cycle the visibility of the OSC? (so that it always shows, as otherwise it keeps making the subtitles move up and down every time it auto-hides and I try to move the mouse over the subtitle causing the OSC to show up again and move the subtitle).

**Comment by ripose-jp** [comment]
Memento's OSC operates independently of mpv's OSC options, but it would be pretty easy to bring it in line with them.
