### ISSUE TITLE
{clipboard-text} or {selection-text}

### ISSUE THREAD

**Issue by Shibasaki175** [ripose-jp/Memento#97]
In Yomichan you have the options {clipboard-text} and {selection-text}. With them you can put only what you want in Anki. It would be cool if they had this in Memento.

**Comment by ripose-jp** [comment]
Memento already has `{clipboard}` which is equivalent to Yomichan's `{clipboard-text}`.

There's not really any selectable text in Memento, so `{selection-text}` doesn't really make sense. It seems like `{context}`, `{context-2}`, `{sentence}`, `{sentence-2}`, and `{cloze-*}` cover anything you'd want to select.

**Comment by Shibasaki175** [comment]
Thanks. I didn't know I had this {clipboard}.

Is there any way to decrease the size of the screenshot that goes to Anki as well? In animebook you can set the screenshot size.

**Comment by ripose-jp** [comment]
No, and I'm not going to add that because there are better ways to resize images on Anki cards such using CSS properties like `max-width`, `max-height`, `width`, and `height` in your templates. See #19.
