### ISSUE TITLE
Unsupported frequency list

### ISSUE THREAD

**Issue by ksesong** [ripose-jp/Memento#99]
The [JPDB Frequency List](https://github.com/MarvNC/jpdb-freq-list) is for some reason unsupported in Memento (while they do work in Yomichan). One can add them to the list of dictionaries without error, but they do not appear in the dictionary entries. This may be due to the inclusion of non-digit characters as ㋕ or ❌ in the frequency value.

**Comment by ripose-jp** [comment]
I'll add support for it today or tomorrow. Should be pretty easy.
